/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// resource.js -	다국어 지원용 resource 모음(China)
//					
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


// 전체 적용되는 리소스 선언
var ID_RES_GLOBAL_DEFAULT_FONT_FAMILY = "Arial";
var ID_RES_GLOBAL_FONT_FAMILY_TYPE_1 = "Arial";

// ComboBox Size Layer(comboboxwin) 리소스 선언
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_8 = "一二三四 ABCD";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_24 = "一二三 ABC";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_36 = "一二 AB";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_MAX = "一二";
var ID_RES_COOMBOBOX_FONT_NAME_0 = "arial";
var ID_RES_COOMBOBOX_FONT_NAME_1 = "Tahoma";
var ID_RES_COOMBOBOX_FONT_NAME_2 = "times new roman";
var ID_RES_COOMBOBOX_FONT_NAME_3 = "verdana";					//10
var ID_RES_COOMBOBOX_FONT_NAME_4 = "comic sans ms";
var ID_RES_COOMBOBOX_FONT_NAME_5 = "courier new";
var ID_RES_COOMBOBOX_FONT_NAME_6 = "";
var ID_RES_COOMBOBOX_FONT_NAME_7 = "";
var ID_RES_COOMBOBOX_FONT_NAME_8 = "";
var ID_RES_COOMBOBOX_FONT_NAME_9 = "";
var ID_RES_COOMBOBOX_FONT_NAME_10 = "";

// 글관련 서식 제거 문구 선언
var ID_RES_COMBOBOX_REMOVE_FONT_FAMILY = "基本";
var ID_RES_COMBOBOX_REMOVE_FONT_SIZE = "基本";
var ID_RES_COMBOBOX_REMOVE_LETTER_SPACING = "基本";				//20
var ID_RES_COMBOBOX_REMOVE_LINE_HEIGHT = "基本";

// 에디터 문자상수(initconst) 리소스 선언
var ID_RES_CONST_STRING_BOLD = "加粗";
var ID_RES_CONST_STRING_ITALIC = "斜体";
var ID_RES_CONST_STRING_UNDERLINE = "下划线";
var ID_RES_CONST_STRING_JUSTIFYLEFT = "居左";
var ID_RES_CONST_STRING_JUSTIFYCENTER = "居中";
var ID_RES_CONST_STRING_JUSTIFYRIGHT = "居右";
var ID_RES_CONST_STRING_JUSTIFYJUSTIFY = "基准线对齐";
var ID_RES_CONST_STRING_ORDERLIST = "加序号";
var ID_RES_CONST_STRING_UNORDERLIST = "句首序号";				//30
var ID_RES_CONST_STRING_STRIKE = "删除线";
var ID_RES_CONST_STRING_SUBSCRIPT = "下添字";
var ID_RES_CONST_STRING_SUPERSCRIPT = "上添字";
var ID_RES_CONST_STRING_OUTDENT = "缩出";
var ID_RES_CONST_STRING_INDENT = "缩进";
var ID_RES_CONST_STRING_UNDO = "取消执行";
var ID_RES_CONST_STRING_REDO = "重新执行";
var ID_RES_CONST_STRING_FONT_NAME = "字体";
var ID_RES_CONST_STRING_FONT_SIZE = "大小";
var ID_RES_CONST_STRING_FORE_COLOR = "前景色";					//40	
var ID_RES_CONST_STRING_BACK_COLOR = "背景色";
var ID_RES_CONST_STRING_TABLE_CREATE = "创建表";
var ID_RES_CONST_STRING_TABLE_ADD_ROW = "加行(Up)";
var ID_RES_CONST_STRING_TABLE_ADD_ROW_DOWN = "加行(Down)";
var ID_RES_CONST_STRING_TABLE_COPY_ROW_DOWN = "加行(Copy)";
var ID_RES_CONST_STRING_TABLE_DELETE_ROW = "删行";
var ID_RES_CONST_STRING_TABLE_ADD_COL = "加列(Left)";
var ID_RES_CONST_STRING_TABLE_ADD_COL_RIGHT = "加列(Right)";
var ID_RES_CONST_STRING_TABLE_DELETE_COL = "删列";
var ID_RES_CONST_STRING_TABLE_MERGE_CELL = "表格合并";			//50
var ID_RES_CONST_STRING_TABLE_SPLIT_ROW = "分行";
var ID_RES_CONST_STRING_TABLE_SPLIT_COL = "分列";
var ID_RES_CONST_STRING_TABLE_SELECT = "选项";

var ID_RES_CONST_STRING_IMAGE_INSERT = "图像插入/属性";
var ID_RES_CONST_STRING_FLASH_INSERT = "FLASH插入/属性";
var ID_RES_CONST_STRING_MEDIA_INSERT = "视频插入/属性";
var ID_RES_CONST_STRING_FULLSCREEN = "全画面";
var ID_RES_CONST_STRING_TABLE_CELL_PROPERTY = "单元格属性";
var ID_RES_CONST_STRING_TABLE_PROPERTY = "表格属性";
var ID_RES_CONST_STRING_MARK_INSERT = "插入特殊字符";			//60
var ID_RES_CONST_STRING_TABLE_TEMPLETE_INSERT = "创建表(模板)";


var ID_RES_CONST_STRING_ADJUST_HWP_BASIC = "韩文更正";
var ID_RES_CONST_STRING_ADJUST_DOC_BASIC = "word更正";
var ID_RES_CONST_STRING_HORIZONTAL_RULE = "插入水平线";
var ID_RES_CONST_STRING_LETTER_SPACING = "字距";
var ID_RES_CONST_STRING_LINE_HEIGHT = "行距";
var ID_RES_CONST_STRING_BODY_BG_COLOR = "文档背景色";
var ID_RES_CONST_STRING_BODY_BG_IMAGE = "文档背景图像";
var ID_RES_CONST_STRING_DOC_TEMPLETE = "插入编辑模块";
var ID_RES_CONST_STRING_PREVIEW = "プレビュー";					//70
var ID_RES_CONST_STRING_HIDE_MINIBAR = "隐藏小框";
var ID_RES_CONST_STRING_WRITE_AREA_SET = "编辑领域设置";
var ID_RES_CONST_STRING_SHOW_EDITABLE_AREA = "编辑领域显示";
var ID_RES_CONST_STRING_SAVEAS = "存储";
var ID_RES_CONST_STRING_PRINT = "打印";
var ID_RES_CONST_STRING_Z_INDEX_SETTING = "设定z-Index";
var ID_RES_CONST_STRING_TEXT_BOX = "字箱";
var ID_RES_CONST_STRING_OBJECT_POSITION = "设定个体Position";
var ID_RES_CONST_STRING_RESPONSIVE_WIDTH = "确认反应性大小";
var ID_RES_CONST_STRING_DOC_LAYOUT = "设定布局";				//80
var ID_RES_CONST_STRING_HEADING_SIZE = "风格";
var ID_RES_CONST_STRING_RESPONSIVE_SET = "统一设定反应性";
var ID_RES_CONST_STRING_FORM_TABLE = "表格编辑模块";
var ID_RES_CONST_STRING_DRAW_TABLE = "绘制表格";



//파일 메뉴 
var ID_RES_CONST_STRING_FILE_NEW				= "新建";
var ID_RES_CONST_STRING_FILE_OPEN				= "打开文件";
var ID_RES_CONST_STRING_FILE_DOCFORM			= "格式样式";
var ID_RES_CONST_STRING_FILE_LAYOUT				= "布局";

//편집 메뉴 
var ID_RES_CONST_STRING_CUT						= "剪切";
var ID_RES_CONST_STRING_COPY					= "复制";		//90
var ID_RES_CONST_STRING_PASTE					= "粘帖";
var ID_RES_CONST_STRING_EDIT_PASTESPECIAL		= "选择粘贴";
var ID_RES_CONST_STRING_DELETE					= "删除";
var ID_RES_CONST_STRING_SELECT_ALL				= "全选";
var ID_RES_CONST_STRING_EDIT_SEARCH				= "查找";
var ID_RES_CONST_STRING_EDIT_REPLACE			= "替换";
var ID_RES_CONST_STRING_REPLACE_CASE			= "转换为大写/小写";

//보기 메뉴 
var ID_RES_CONST_STRING_VIEW_EDIT				= "编辑窗口";
var ID_RES_CONST_STRING_VIEW_HTML				= "代码窗口";

//삽입 메뉴 
var ID_RES_CONST_STRING_INSERT_IMAGE			= "图像";		//100
var ID_RES_CONST_STRING_INSERT_OBJECT			= "个体";
var ID_RES_CONST_STRING_INSERT_SPECIALCHARS		= "插入特殊字符";
var ID_RES_CONST_STRING_INSERT_BOOKMARK			= "书签";
var ID_RES_CONST_STRING_INSERT_EMOTICONS		= "表情符号";
var ID_RES_CONST_STRING_HYPERLINK_INSERT		= "超级链接";
var ID_RES_CONST_STRING_HYPERLINK_MODIFY		= "超级链接";
var ID_RES_CONST_STRING_HYPERLINK_REMOVE		= "删除链接";

//서식 메뉴 
var ID_RES_CONST_STRING_STYLE_FONT				= "文字模样";
var ID_RES_CONST_STRING_STYLE_PARAGRAPH			= "文段模样";
var ID_RES_CONST_STRING_STYLE_STYLE				= "风格";		//110
var ID_RES_CONST_STRING_STYLE_UNORDEREDLIST		= "句首序号";
var ID_RES_CONST_STRING_STYLE_ORDEREDLIST		= "加序号";
var ID_RES_CONST_STRING_STYLE_INCREASEORDER		= "增加一阶段";
var ID_RES_CONST_STRING_STYLE_DECREASEORDER		= "减少一阶段";

//표 메뉴 
var ID_RES_CONST_STRING_TABLE_CELL_STYLE		= "单元格边框/背景";
var ID_RES_CONST_STRING_TABLE_ADD_ROW_COL		= "添加列/格";
var ID_RES_CONST_STRING_TABLE_DELETE_ROW_COL	= "删除列/格";
var ID_RES_CONST_STRING_TABLE_SPLIT_CELL		= "拆分单元格";
var ID_RES_CONST_STRING_TABLE_CELL_SAME_HEIGHT	= "统一单元格的高度";	//120
var ID_RES_CONST_STRING_TABLE_CELL_SAME_WIDTH	= "统一单元格的宽度";
var ID_RES_CONST_STRING_TABLE_CELL_ALIGN		= "整列单元格";
var ID_RES_CONST_STRING_TABLE_MADANG			= "表格";
var ID_RES_CONST_STRING_TABLE_FORMULA			= "计算式";
var ID_RES_CONST_STRING_TABLE_NUMBER_FORMAT		= "区分1,000单位的逗号";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICALALIGN	= "纵向整列单元格";

var ID_RES_CONST_STRING_TABLE_BLOCK_FORMULA		= "模块计算式";
var ID_RES_CONST_STRING_TABLE_FORMULA			= "计算式";
var ID_RES_CONST_STRING_TABLE_SELECT_FORMULA	= "选择计算式";
var ID_RES_CONST_STRING_TABLE_EASY_FORMULA	= "容易的计算式";

//도움말
var ID_RES_CONST_STRING_HELP_SHORTCUTS = "快捷键";				//130
var ID_RES_CONST_STRING_HELP = "产品帮助";
var ID_RES_CONST_STRING_PRODUCT_INFO = "产品信心";


//2depth 메뉴
var ID_RES_CONST_STRING_INSERT_OBJECT_MOVIE = "视频插入";
var ID_RES_CONST_STRING_INSERT_OBJECT_FILE = "文件";
var ID_RES_CONST_STRING_INSERT_OBJECT_HR = "插入水平线";

var ID_RES_CONST_STRING_STYLE_STYLE_BASIC = "基本";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT1 = "标题1";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT2 = "标题2";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT3 = "标题3";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT4 = "标题4";			//140
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT5 = "标题5";

var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_TOP = "上对齐对齐";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_MIDDLE = "居中对齐";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_BOTTOM = "下对齐对齐";

var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTALALIGN	= "横向整列单元格";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_LEFT = "左边";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_CENTER = "居中";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_RIGHT = "右边";

var ID_RES_CONST_STRING_TABLE_BLOCK_SUM = "模块合计";
var ID_RES_CONST_STRING_TABLE_BLOCK_AVG = "模块平均";				//150
var ID_RES_CONST_STRING_TABLE_BLOCK_MUL = "模块乘积";

var ID_RES_CONST_STRING_TABLE_HORIZONTAL_SUM = "横向合计";
var ID_RES_CONST_STRING_TABLE_VERTICAL_SUM = "纵向合计";
var ID_RES_CONST_STRING_TABLE_HORIZONTAL_AVERAGE = "横向平均";
var ID_RES_CONST_STRING_TABLE_VERTICAL_AVERAGE = "纵向平均";
var ID_RES_CONST_STRING_TABLE_HORIZONTAL_MULTIPLY = "横向乘积";
var ID_RES_CONST_STRING_TABLE_VERTICAL_MULTIPLY = "纵向乘积";

var ID_RES_CONST_STRING_TABLE_ADD_NUMBER_FORMAT = "插入定位点";
var ID_RES_CONST_STRING_TABLE_REMOVE_NUMBER_FORMAT = "抽出定位点";


//-- 툴바에만 존재하는 버튼
var ID_RES_CONST_STRING_STYLE_INCREASE_FONTSIZE = "放大字体大小";	//160
var ID_RES_CONST_STRING_STYLE_DECREASE_FONTSIZE = "缩小字体大小";

// 폼태그 버튼
var ID_RES_CONST_STRING_FORM_TAG_SWITCH = "选择转换样式控制";
var ID_RES_CONST_STRING_FORM_TAG_CHECKBOX = "被选箱子";
var ID_RES_CONST_STRING_FORM_TAG_SELECT = "目录箱子";

// 양식 템플릿
var ID_RES_CONST_STRING_TEMPLETE_FORM = "样式模板";

// 빈문단삽입
var ID_RES_CONST_STRING_INSERT_PARAGRAPH_STARTPOINT = "插入开始点文段";
var ID_RES_CONST_STRING_INSERT_PARAGRAPH_ENDPOINT = "插入结束点文段";

// 표 삭제
var ID_RES_CONST_STRING_TABLE_DELETE_TABLE = "删除表";

// 삽입 - 문단
var ID_RES_CONST_STRING_INSERT_PARAGRAPH = "文段";

// 서식 - 글자모양 - 보통모양 버튼 텍스트
var ID_RES_CONST_STRING_NORMAL = "普通模样";						//170

//표 - 표 텍스트로 변환
var ID_RES_CONST_STRING_TABLE_CONVERT_TEXT = "转换为表格文字";

// 테이블생성 Layer(tablesize) 리소스 선언
var ID_RES_TABLE_SIZE_SELECT = "选择";
var ID_RES_TABLE_SIZE_CANCEL = "取消";

// 툴빌더(toolbuilder) 리소스 선언
var ID_RES_TOOL_STRING_MENU_FILE = "文件";
var ID_RES_TOOL_STRING_MENU_EDIT = "编辑";
var ID_RES_TOOL_STRING_MENU_VIEW = "预览";
var ID_RES_TOOL_STRING_MENU_INSERT = "插入";
var ID_RES_TOOL_STRING_MENU_BASIC = "格式";
var ID_RES_TOOL_STRING_MENU_TABLE = "表格";
var ID_RES_TOOL_STRING_MENU_HELP = "帮助";						//180
var ID_RES_TOOL_STRING_TAB_PREVIEW = "预览";
var ID_RES_TOOL_STRING_TAB_EDIT = "编辑窗口";
var ID_RES_TOOL_STRING_TAB_SOURCE = "代码窗口";

// 사용자메세지(usermsg) 리소스 선언
var ID_RES_USER_MSG_STRING_ALERT_CUT = "因为浏览器安全设置问题, 不能执行\n可通过键盘按键Ctrl+X 执行命令";
var ID_RES_USER_MSG_STRING_ALERT_COPY = "因为浏览器安全设置问题, 不能执行\n可通过键盘按键Ctrl+C 执行命令";
var ID_RES_USER_MSG_STRING_ALERT_PASTE = "因为浏览器安全设置问题, 不能执行\n可通过键盘按键Ctrl+V 执行命令";
var ID_RES_USER_MSG_STRING_WARNING_SCRIPT = "代码中不能包括脚本\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_MEDIA = "视频插入仅支持IE 6,7,8\n";
var ID_RES_USER_MSG_STRING_WARNING_NO_IFRAME = "代码中无能包括 iframe 标签\n";
var ID_RES_USER_MSG_STRING_WARNING_NO_SOURCE_EDIT = "格式用户模式下不能使用代码窗口\n";	//190
//var ID_RES_USER_MSG_STRING_WARNING_NO_FLASH_FF_2 = "支持 Firefox 3版本以上\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_FLASH_FF_EDIT = "不支持 Firefox 编辑模式设置\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_SUPPORT_FORM_MODE = "代码检查在格式管理员或用户模式下不能使用\n";
//var ID_RES_USER_MSG_STRING_WARNING_INVALID_ATTIRIBUTE_CHARACTER = "属性值不能使用 <,>,&,\',\" 等符号\n";
//var ID_RES_USER_MSG_STRING_WARNING_INVALID_COLOR_CODE = "유효한 색상코드를 입력하셔야 합니다.\n 예) #0099ff\n";
//var ID_RES_USER_MSG_STRING_WARNING_IN_CONTROL_KEY_NO_SOURCE_EDIT = "키보드 제어용에서는 소스창을 사용할 수 없습니다";

// 문서보정(leftviewui) 리소스 선언
var ID_RES_ADJUST_VIEW_CLOSE = "关闭";

// 편집창 Title 리소스 선언
var ID_RES_EDIT_TITLE_STRING = "文章输入部分";

var ID_RES_PROP_BUILDER_BLOCK_PROP_ITEM_APPLY = "适用";

var ID_RES_CONST_STRING_ALIGN = "对齐";							//200

// 양식 저작(Form Table) 리소스 선언
var ID_RES_PROP_FORM_WIN_TITLE = "样式布局";
var ID_RES_PROP_TAG_SELECT_WIN_TITLE = "目录箱子";
var ID_RES_PROP_MAPPING_CODE_WIN_TITLE = "样式代码";
var ID_RES_PROP_MAPPING_CSS_WIN_TITLE = "设定样式CSS";
var ID_RES_PROP_TEMPLETE_FORM_WIN_TITLE = "样式模板";

// 컨텍스트 메뉴
var ID_RES_PROP_INSERT_IMAGE = "图片属性";
var ID_RES_PROP_INSERT_FILE = "加载的文件属性";

var ID_RES_DIALOG_BTN_OK = "确认";
var ID_RES_DIALOG_BTN_CANCEL = "取消";
var ID_RES_DIALOG_BTN_NOCOLOR = "无颜色";							//210
var ID_RES_DIALOG_TAB_GENERAL = "一般";
var ID_RES_DIALOG_TAB_BORDER = "边框";
var ID_RES_DIALOG_TAB_BACKGROUND = "背景";
var ID_RES_DIALOG_FORM_LIST1 = "样本项目1";
var ID_RES_DIALOG_FORM_LIST2 = "样本项目2";
var ID_RES_DIALOG_FORM_LIST3 = "样本项目3";
var ID_RES_DIALOG_MAPPINGCODE_TAB1 = "电子审批样式";
var ID_RES_DIALOG_MAPPINGCODE_TAB2 = "公文样式";
var ID_RES_DIALOG_CONFIRM_SAVE = "<p>有正在编写中的内容。</p><p>要保存吗?</p>";
var ID_RES_DIALOG_CONFIRM_YES = "是";							//220
var ID_RES_DIALOG_CONFIRM_NO = "否";
var ID_RES_DIALOG_CONFIRM_EMPTY_DOC = "文件为空，请确认。";
var ID_RES_DIALOG_ALERT_SELECTFILE = "请选择文件。";
var ID_RES_DIALOG_CONFIRM_FILE_DELETE_CONTENT = "若读取文件，填写中的内容将会被删除，\n要读取文件吗？";
var ID_RES_DIALOG_ALERT_ALLOWFILES = "无法上传文件。\n可以上传的文件";
var ID_RES_DIALOG_ALERT_SELECTIMAGE = "请选择图片文件之后点击上传按键。";
var ID_RES_DIALOG_ALERT_SELECT_VALID_IMAGE = "请插入正常图片。";
var ID_RES_DIALOG_ALERT_FIND_INPUT_TEXT = "请输入要查询的内容。";
var ID_RES_DIALOG_ALERT_FIND_ERROR = "搜索中发生错误。";
var ID_RES_DIALOG_ALERT_FIND_NOTHING = "没有找到该内容。";		//230
var ID_RES_DIALOG_CONFIRM_FIND_END = "已查找到文章最后。\n从文章开头开始继续查找吗？";
var ID_RES_DIALOG_CONFIRM_FIND_FIRST = "已查找到文章开头。\n从文章最后开始继续查找吗？";
var ID_RES_DIALOG_ALERT_REPLACE_INPUT_TEXT = "请输入要替换的内容。";
var ID_RES_DIALOG_ALERT_REPLACE_ERROR = "替换中发生错误。";
var ID_RES_DIALOG_ALERT_REPLACEALL_COMPLETE = "已替换所有。";
var ID_RES_DIALOG_ALERT_REPLACE_N = "替换   个项目。";
var ID_RES_DIALOG_TITLE_FIND_REPLACE = "查找/替换";
var ID_RES_DIALOG_BTN_REPLACEALL = "全部替换";
var ID_RES_DIALOG_BTN_FIND_NEXT = "查找";
var ID_RES_DIALOG_TITLE_EXT_MOVIE = "外部视频";					//240
var ID_RES_DIALOG_TITLE_FILE_INSERT = "导入自动保存内容";
var ID_RES_DIALOG_BTN_INSERT = "添加";
var ID_RES_DIALOG_TITLE_WEBEDITOR_INFO = "Douzone Web Editor 信息";

var ID_RES_DIALOG_LIST_TITLE_FORM_AREA = "样式领域";
var ID_RES_DIALOG_LIST_TITLE_FORM_SELECT = "选择样式";
var ID_RES_DIALOG_ALERT_SELECT_DOCFORM = "请选择格式样式。";
var ID_RES_DIALOG_CONFIRM_DOCFORM_DELETE_CONTENT = "若插入格式样式，编辑中的文件将会被删除，\n要插入吗？";
var ID_RES_DIALOG_ALERT_SELECT_LAYOUT_DESIGN = "请选择布局设计。";
var ID_RES_DIALOG_CONFIRM_LAYOUT_DELETE_CONTENT = "若插入布局，编辑中的文件将会被删除，\n要插入吗？";

var ID_RES_DIALOG_STRING_FILE_PATH = "文件路径";					//250
var ID_RES_DIALOG_STRING_URL_INPUT = "插入网址";
var ID_RES_DIALOG_STRING_UPLOAD = "上传";
var ID_RES_DIALOG_STRING_SIZE = "大小";
var ID_RES_DIALOG_STRING_WIDTH = "宽度";
var ID_RES_DIALOG_STRING_HEIGHT = "高度";
var ID_RES_DIALOG_STRING_KEEP_RATIO = "维持宽度/高度比例";
var ID_RES_DIALOG_STRING_SET_ORG = "保持其原始大小";
var ID_RES_DIALOG_STRING_MARGIN = "空白";
var ID_RES_DIALOG_STRING_MARGIN_LEFT = "左空白";
var ID_RES_DIALOG_STRING_MARGIN_TOP = "上空白";					//260
var ID_RES_DIALOG_STRING_MARGIN_RIGHT = "右空白";
var ID_RES_DIALOG_STRING_MARGIN_BOTTOM = "下空白";
var ID_RES_DIALOG_STRING_ALIGN_BASIC = "基本值";
var ID_RES_DIALOG_STRING_ALIGN_LEFT = "左边";
var ID_RES_DIALOG_STRING_ALIGN_CENTER = "居中";
var ID_RES_DIALOG_STRING_ALIGN_RIGHT = "右边";
var ID_RES_DIALOG_ALERT_MAX_VALUE = "已超过最大值。\n最大值：";
var ID_RES_DIALOG_ALERT_MIN_VALUE = "已超过最小值。\n最小值：";
var ID_RES_DIALOG_ALERT_NUMBER_ONLY = "只可以输入数字。";
var ID_RES_DIALOG_ALERT_SELECT_VALID_URL = "请再次确认图片的URL！";	//270
var ID_RES_DIALOG_ALERT_UPLOAD_ERROR = "上传时发生错误，请重试。";
var ID_RES_DIALOG_ALERT_INSERT_IMAGE = "请先登录图片。";
var ID_RES_DIALOG_STRING_NO_STYLE_TEXT = "没有格式的文字";
var ID_RES_DIALOG_STRING_HTML_STYLE_TEXT = "HTML 形式";
var ID_RES_DIALOG_STRING_FIND_TEXT = "查找的内容";
var ID_RES_DIALOG_STRING_REPLACE_TEXT = "替换的内容";
var ID_RES_DIALOG_STRING_FIND_OPTION = "搜索选项";
var ID_RES_DIALOG_STRING_CASESENSITIVE = "大小写区分";
var ID_RES_DIALOG_STRING_COMPLETEWORD = "按词语单位";
var ID_RES_DIALOG_STRING_IGNORESPACE = "忽略空格";				//280
var ID_RES_DIALOG_STRING_FIND_DERECTION = "搜索方向";
var ID_RES_DIALOG_STRING_FIND_DOWN = "向下";
var ID_RES_DIALOG_STRING_FIND_UP = "向上";
var ID_RES_DIALOG_STRING_INPUT_SOURCE = "源输入";
var ID_RES_DIALOG_STRING_MOVIE_INPUT_GUIDE = "请输入object或者iframe来源代码。";
var ID_RES_DIALOG_STRING_INPUT_MOVIE_SOURCE = "请输入视频代码。";
var ID_RES_DIALOG_STRING_VIEW_TEXT = "显示的文本";
var ID_RES_DIALOG_ALERT_ALLOW_FORMAT = "只支持格式。";
var ID_RES_DIALOG_STRING_CHARACTER_AREA = "文字领域";
var ID_RES_DIALOG_STRING_CHARACTER_SELECT = "文字选择";			//290
var ID_RES_DIALOG_STRING_RECECT_USE_CHARACTER = "最近使用的文字";

var ID_RES_DIALOG_ALERT_SELECT_CHARACTER = "请选择文字。";
var ID_RES_CONST_STRING_CHARACTER_GENERAL = "一般/符号";
var ID_RES_CONST_STRING_CHARACTER_ENG_NUMBER = "英文/数字";
var ID_RES_CONST_STRING_CHARACTER_GREEK = "希腊语";
var ID_RES_CONST_STRING_CHARACTER_LINE = "线文字";
var ID_RES_CONST_STRING_CHARACTER_UNIT = "单位符号";
var ID_RES_CONST_STRING_CHARACTER_CIRCLE = "圆文字";
var ID_RES_CONST_STRING_CHARACTER_BRAKETCHAR = "括号文字";
var ID_RES_CONST_STRING_CHARACTER_FRACTION_SCRIPT = "分数/脚注";	//300
var ID_RES_CONST_STRING_CHARACTER_ARROW = "箭头";
var ID_RES_CONST_STRING_CHARACTER_BRAKET = "括号";
var ID_RES_CONST_STRING_CHARACTER_MATH = "数学演算";
var ID_RES_CONST_STRING_CHARACTER_PUNCTUATION_MARKS = "文章符号";
var ID_RES_CONST_STRING_CHARACTER_CURRENCY = "货币符号";

var ID_RES_DIALOG_STRING_BOOKMARK_NAME = "书签名称";
var ID_RES_DIALOG_STRING_BOOKMARK_LIST = "书签目录";
var ID_RES_DIALOG_STRING_MOVE = "移动";							//310
var ID_RES_DIALOG_STRING_BOOKMARK_SORT_STANDARD = "书签整列标准";
var ID_RES_DIALOG_STRING_NAME = "姓名";
var ID_RES_DIALOG_STRING_POSITION = "位置";
var ID_RES_DIALOG_ALERT_INPUT_BOOKMARK_NAME = "请输入书页的名字。";
var ID_RES_DIALOG_ALERT_INPUT_SELECT_DELTE_BOOKMARK_ITEM = "在书签目录中请选择要删除的项目。";
var ID_RES_DIALOG_ALERT_INPUT_SELECT_MOVE_BOOKMARK_ITEM = "在书签目录中请选择要移动的项目。";

var ID_RES_DIALOG_STRING_LINK_TYPE = "链接种类";
var ID_RES_DIALOG_STRING_WEB_ADDR = "网页地址";
var ID_RES_DIALOG_STRING_LINK_TARGET = "打开链接文件";
var ID_RES_DIALOG_STRING_LINK_CURRENT_WINDOW = "以同样的窗口";
var ID_RES_DIALOG_STRING_LINK_NEW_WINDOW = "打开新窗";
var ID_RES_DIALOG_STRING_LINK_NO_CONNECT = "不连接";				//320
var ID_RES_DIALOG_STRING_LIST_SELECT = "选择";
var ID_RES_DIALOG_ALERT_SELECT_BOOKMARK = "请选择书页。";
var ID_RES_DIALOG_ALERT_INPUT_WEB_ADDR = "请输入网页地址。";

var ID_RES_DIALOG_STRING_LETTERSPACING = "字间";
var ID_RES_DIALOG_STRING_BASIC = "基本";
var ID_RES_DIALOG_STRING_PROPERTY = "属性";
var ID_RES_DIALOG_STRING_FONT_STYLE_PREVIEW = "一二三ABCabc123※○";

var ID_RES_DIALOG_STRING_ALIGN_TYPE = "整列方式";
var ID_RES_DIALOG_STRING_NORMAL = "普通";
var ID_RES_DIALOG_STRING_SPACING = "间隔";						//330
var ID_RES_DIALOG_STRING_LINEHEIGHT = "行数";
var ID_RES_DIALOG_STRING_PARAGRAPH_TOP = "文章单位";
var ID_RES_DIALOG_STRING_PARAGRAPH_BOTTOM = "文段下面";
var ID_RES_DIALOG_STRING_FIRST_PARAGRAPH = "第一行";

var ID_RES_DIALOG_STRING_NONE = "无";
var ID_RES_DIALOG_STRING_VERSION = "版本";


var ID_RES_DIALOG_STRING_FORM_BASE_SIZE = "标准大小/高度";
var ID_RES_DIALOG_STRING_FORM_HEIGHT_MSG = "创建样式时反应高度设定";
var ID_RES_DIALOG_STRING_FORM_OUTLINE = "外界线";
var ID_RES_DIALOG_STRING_FORM_TYPE = "类型";						//340
var ID_RES_DIALOG_STRING_FORM_COLOR = "颜色";
var ID_RES_DIALOG_STRING_FORM_MULTI_SELECT = "多种选择：<br />&nbsp;&nbsp;Ctrl键+选择对象";
var ID_RES_DIALOG_STRING_FORM_MULTI_OTHER_SELECT = "多种选择：<br />&nbsp;&nbsp;选择对象->shift键-><br />&nbsp;&nbsp;选择其他对象";
var ID_RES_DIALOG_STRING_FORM_COPY_PASTE = "复制/粘贴 :<br />&nbsp;&nbsp;选择对象后Ctrl键+V";
var ID_RES_DIALOG_STRING_FORM_COPY_MOVE = "移动 :<br />&nbsp;&nbsp;上下左右箭头键";
var ID_RES_DIALOG_STRING_FORM_RESIZE = "调整大小 :<br />&nbsp;&nbsp;Ctrl键+箭头键";
var ID_RES_DIALOG_STRING_FORM_PRE_APPLY = "预先适用";
var ID_RES_DIALOG_ALERT_FORM_SIZE = "只支持大小(width)单位为%的情况。";

var ID_RES_PROP_TAG_STRING_ROW_NUM = "横线数";
var ID_RES_PROP_TAG_STRING_COL_NUM = "列数";						//350
var ID_RES_PROP_TAG_STRING_ROW_COL = "列/格";
var ID_RES_PROP_TAG_STRING_SIZE_DEFINE = "指定大小";
var ID_RES_PROP_TAG_STRING_WIDTH_UNIT = "宽度单位";
var ID_RES_PROP_TAG_STRING_ALL_CELL_INNER_MARGIN = "所有单元格的内白边";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN = "整列";

var ID_RES_PROP_TAG_STRING_TABLE_ALIGN_NONE = "无";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN_LEFT = "左边";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN_CENTER = "中间";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN_RIGHT = "右边";

var ID_RES_PROP_TAG_STRING_FILL = "填充";						//360
var ID_RES_PROP_TAG_STRING_NO_COLOR_FILL = "没有填充颜色";
var ID_RES_PROP_TAG_STRING_COLOR = "色";
var ID_RES_PROP_TAG_STRING_FACE_COLOR = "面颜色";

var ID_RES_PROP_TAG_STRING_IMAGE = "图片";
var ID_RES_PROP_TAG_STRING_USER_IMAGE = "使用图片";
var ID_RES_PROP_TAG_STRING_IMAGE_FILE = "图片文件";
var ID_RES_PROP_TAG_STRING_FILL_TYPE = "填充类型";
var ID_RES_PROP_TAG_STRING_REPEAT = "重复";
var ID_RES_PROP_TAG_STRING_REPEAT_HOR = "横向反复";
var ID_RES_PROP_TAG_STRING_REPEAT_VER = "纵向反复";				//370
var ID_RES_PROP_TAG_STRING_REPEAT_NO = "不反复";

var ID_RES_PROP_TAG_LIST_NUM = "目录个数";
var ID_RES_PROP_TAG_LIST_CONTENT = "目录内容";

var ID_RES_PROP_TAG_ADD_ROW = "添加列";
var ID_RES_PROP_TAG_UP = "向上";
var ID_RES_PROP_TAG_DOWN = "向下";
var ID_RES_PROP_TAG_ADD_COL = "添加列";

var ID_RES_PROP_TAG_SET_INNER_MARGIN = "指定内部白边";

var ID_RES_PROP_TAG_STRING_LEFT = "左对齐";
var ID_RES_PROP_TAG_STRING_TOP = "向上";						//380
var ID_RES_PROP_TAG_STRING_RIGHT = "右对齐";
var ID_RES_PROP_TAG_STRING_BOTTOM = "向下";

var ID_RES_PROP_TAG_STRING_ALIGN_HOR = "水平对齐";
var ID_RES_PROP_TAG_STRING_ALIGN_VER = "垂直对齐";
var ID_RES_PROP_TAG_STRING_ALIGN_TOP = "上对齐对齐";
var ID_RES_PROP_TAG_STRING_ALIGN_MIDDLE = "居中对齐";
var ID_RES_PROP_TAG_STRING_ALIGN_BOTTOM = "下对齐对齐";

var ID_RES_PROP_TAG_STRING_APPLY_RANGE= "适用范围";
var ID_RES_PROP_TAG_STRING_SELECTED_CELL = "被选的单元格";
var ID_RES_PROP_TAG_STRING_ALL_CELL = "所有单元格";					//390

var ID_RES_PROP_TAG_ALERT_UNDER_100PER = "请设定为100%以下。";

var ID_RES_PROP_TAG_STRING_SELECT_CELL_EDITOR = "在编辑窗口中请选择要适用的单元格。";
var ID_RES_PROP_TAG_STRING_NO_CALC_SELECTED_CELL = "选择了无法计算的项目。";
var ID_RES_PROP_TAG_STRING_SELECT_CELL = "选择单元格";
var ID_RES_PROP_TAG_STRING_CALC_TYPE = "计算方法";
var ID_RES_PROP_TAG_STRING_CALC_SUM = "合计";
var ID_RES_PROP_TAG_STRING_CALC_AVG = "平均";
var ID_RES_PROP_TAG_STRING_CALC_MUL = "乘积";
var ID_RES_PROP_TAG_STRING_CALC_RESULT = "计算结果";
var ID_RES_PROP_TAG_STRING_SPLIT_ROW_COL = "分离列/格";			//400

var ID_RES_PROP_TEMPLETE_STRING_FORM_SUBJECT = "样式标题";
var ID_RES_PROP_TEMPLETE_STRING_SUBJECT = "标题";
var ID_RES_PROP_TEMPLETE_STRING_SIZE_ITEM_SET = "设定大小/项目";
var ID_RES_PROP_TEMPLETE_STRING_AUTO = "自动";
var ID_RES_PROP_ALERT_ONLY_NUMBER_CALC = "只可以计算数字。";

var ID_RES_DIALOG_SHORTCUTS_TITLE = "快捷键";
var ID_RES_DIALOG_SHORTCUTS_MENU_PATH = "菜单途径";
var ID_RES_DIALOG_SHORTCUTS_FUNCTION = "功能";
var ID_RES_DIALOG_SHORTCUTS_BASIC = "标准快捷键";
var ID_RES_DIALOG_SHORTCUTS_SPACE = "插入空格";					//410
var ID_RES_DIALOG_SHORTCUTS_ENTER = "分离文段";
var ID_RES_DIALOG_SHORTCUTS_LEFT = "向左移动一个字段";
var ID_RES_DIALOG_SHORTCUTS_RIGHT = "向右移动一个字段";
var ID_RES_DIALOG_SHORTCUTS_DOWN = "向下挪一行";
var ID_RES_DIALOG_SHORTCUTS_UP = "向上挪一行";
var ID_RES_DIALOG_SHORTCUTS_RIGHT_WORD = "向右移动一个单词";
var ID_RES_DIALOG_SHORTCUTS_LEFT_WORD = "向左移动一个单词";
var ID_RES_DIALOG_SHORTCUTS_DOWN_PARAGRAPH = "向下挪一个文段";
var ID_RES_DIALOG_SHORTCUTS_UP_PARAGRAPH = "向上挪一个文段";
var ID_RES_DIALOG_SHORTCUTS_HOME = "移动到列前";					//420
var ID_RES_DIALOG_SHORTCUTS_END = "移动到列端";
var ID_RES_DIALOG_SHORTCUTS_HOME_PAGE = "转到首页";
var ID_RES_DIALOG_SHORTCUTS_END_PAGE = "转到末页";
var ID_RES_DIALOG_SHORTCUTS_DELETE = "删除后字";
var ID_RES_DIALOG_SHORTCUTS_BACKSPACE = "删除前字";
var ID_RES_DIALOG_SHORTCUTS_DELETE_WORD = "删除一个单词";
var ID_RES_DIALOG_SHORTCUTS_DELETE_PREV_WORD = "删除前一个单词";

var ID_RES_DIALOG_SHORTCUTS_FILE = "文件菜单";
var ID_RES_DIALOG_SHORTCUTS_EDIT = "编辑菜单";
var ID_RES_DIALOG_SHORTCUTS_INSERT = "插入菜单";					//430
var ID_RES_DIALOG_SHORTCUTS_STYLE = "格式菜单";
var ID_RES_DIALOG_SHORTCUTS_TABLE = "表格菜单";

var ID_RES_CONST_STRING_CLEAR = "发布";

var ID_RES_CONST_STRING_INCREASE_LETTERSPACING = "放大字间距离";
var ID_RES_CONST_STRING_DECREASE_LETTERSPACING = "缩小字间距离";

var ID_RES_CONST_STRING_INCREASE_MARGIN_LEFT = "放大左白边";
var ID_RES_CONST_STRING_DECREASE_MARGIN_LEFT = "缩小左白边";
var ID_RES_CONST_STRING_INCREASE_MARGIN_RIGHT = "放大右白边";
var ID_RES_CONST_STRING_DECREASE_MARGIN_RIGHT = "缩小右白边";

var ID_RES_CONST_STRING_FIRST_PARAGRAPH_OUTDENT = "多处一行";	//440
var ID_RES_CONST_STRING_FIRST_PARAGRAPH_INDENT = "缩进一行";

var ID_RES_CONST_STRING_INCREASE_LINEHEIGHT = "放大列间隔";
var ID_RES_CONST_STRING_DECREASE_LINEHEIGHT = "缩小列间隔";

var ID_RES_CONST_STRING_SELECT_CURRENT_CELL = "选择当前单元格";
var ID_RES_CONST_STRING_MOVE_CELL_UNIT = "以单元格单位移动光标";
var ID_RES_CONST_STRING_MOVE_NEXT_CELL = "在表格中向其他单元格移动(正方向)";
var ID_RES_CONST_STRING_MOVE_PREV_CELL = "在表格中向其他单元格移动(逆方向)";

var ID_RES_CONST_STRING_BLOCK_ALL_COL = "格所有模块";
var ID_RES_CONST_STRING_BLOCK_ALL_ROW = "列所有模块";
var ID_RES_CONST_STRING_MULTI_CELL_SELECT = "选择多个单元格时";		//450
var ID_RES_CONST_STRING_ARROW_KEY = "方向键";

var ID_RES_CONST_STRING_STANDARD = "标准";
var ID_RES_CONST_STRING_USER_DEFINE = "习惯";
var ID_RES_CONST_STRING_USER_SET = "习惯";
var ID_RES_CONST_STRING_REPLACE_CASE_CAPITAL = "都转化为大写";
var ID_RES_CONST_STRING_REPLACE_CASE_SMALL = "都转换为小写";
var ID_RES_CONST_STRING_REPLACE_CASE_REVERSE = "替换大写和小写";
var ID_RES_CONST_STRING_REPLACE_CASE_LETTER = "首字母转换为大写";
var ID_RES_CONST_STRING_REPLACE_CASE_SENTENCE = "文章第一个字替换为大写";
var ID_RES_CONST_STRING_REPLACE_CASE_PARAGRAPH = " 文段第一个字替换为大写";	//460
var ID_RES_CONST_BTN_DELETE = "删除";
var ID_RES_CONST_INSERT_IMAGE_PARAGRAPH_ALIGN = "整列本文";

var ID_RES_CONST_STRING_NEW_COLOR = "新的颜色";
var ID_RES_CONST_STRING_CURRENT_COLOR = "当前颜色";
var ID_RES_CONST_STRING_OTHER_COLOR = "其他颜色";
var ID_RES_CONST_STRING_RECENT_COLOR = "最近使用的颜色";
var ID_RES_CONST_STRING_ADD_USER_COLOR = "添加到用户指定的颜色中";
var ID_RES_CONST_STRING_RED = "红色";
var ID_RES_CONST_STRING_GREEN = "绿色";
var ID_RES_CONST_STRING_BLUE = "蓝色";								//470
var ID_RES_CONST_STRING_HUE = "颜色";
var ID_RES_CONST_STRING_SATURATION = "彩度";
var ID_RES_CONST_STRING_LIGHTNESS = "明度";

var ID_RES_CONST_MSG_ALERT_NO_RECENT_COLOR = "没有最近使用的颜色。";
var ID_RES_CONST_MSG_ALERT_DELETE_RECENT_COLOR = "要删除最近使用的所有颜色吗？";

var ID_RED_CONST_STRING_ALIGN_LEFT_TOP		= "左上";
var ID_RED_CONST_STRING_ALIGN_LEFT_MIDDLE	= "左中";
var ID_RED_CONST_STRING_ALIGN_LEFT_BOTTOM	= "左下";
var ID_RED_CONST_STRING_ALIGN_CENTER_TOP	= "上中";
var ID_RED_CONST_STRING_ALIGN_CENTER_MIDDLE = "正中";				//480
var ID_RED_CONST_STRING_ALIGN_CENTER_BOTTOM = "下中";
var ID_RED_CONST_STRING_ALIGN_RIGHT_TOP		= "右上";
var ID_RED_CONST_STRING_ALIGN_RIGHT_MIDDLE	= "右中";
var ID_RED_CONST_STRING_ALIGN_RIGHT_BOTTOM	= "右下";
var ID_RED_CONST_STRING_TABLE_CELL_BACKCOLOR	= "单元格背景颜色";

var ID_RES_CONST_STRING_COLOR_STANDARD = "标准颜色";
var ID_RES_CONST_STRING_COLOR_THEME = "主体颜色";

var ID_RES_CONST_STRING_EMOTICONS_FEEL = "感情";
var ID_RES_CONST_STRING_EMOTICONS_ACTION = "行动";
var ID_RES_CONST_STRING_EMOTICONS_ETC = "其他";						//490
var ID_RES_DIALOG_STRING_CATEGORY_AREA = "分类";
var ID_RES_DIALOG_STRING_EMOTICON_SELECT = "选择表情符号";
var ID_RES_DIALOG_STRING_RECECT_USE_EMOTICONS = "最近使用的表情符号";

var ID_RES_UI_TOGGLE_STRING_RIBBON = "自定义菜单样式";
var ID_RES_UI_TOGGLE_STRING_TOOLBAR = "工具栏菜单样式";
var ID_RES_CONST_STRING_PRINT_PAGE_BREAK = "划分打印页面";
var ID_RES_CONST_STRING_VIEW_RULERBAR = "显示标尺";
var ID_RES_DIALOG_STRING_CASCADE_ORDERLIST = "分步目录";
var ID_RES_CONST_STRING_COPY_EXT_STYLE = "复制样式";

var ID_RES_CONST_STRING_BORDER_TYPE = "边线种类";					//500
var ID_RES_CONST_STRING_BORDER_THICKNESS = "边线厚度";
var ID_RES_CONST_STRING_BORDER_COLOR = "边线颜色";
var ID_RES_CONST_STRING_RESET_PICTURE = "Reset a picture";

var ID_RES_CONST_STRING_NO_LINE = "除线";
var ID_RES_CONST_STRING_SOLID_LINE = "实线";
var ID_RES_CONST_STRING_DASHED_LINE = "波线";
var ID_RES_CONST_STRING_DOTTED_LINE = "虚线";
var ID_RES_CONST_STRING_DOUBLE_LINE = "双重线";

var ID_RES_CONST_STRING_TABLE_SELECT_CELL = "选择单元格";
var ID_RES_CONST_STRING_TABLE_SELECT_COL = "选择列";				//510
var ID_RES_CONST_STRING_TABLE_SELECT_ROW = "选择行";
var ID_RES_CONST_STRING_TABLE_SELECT_TABLE = "选择表格";

var ID_RES_CONST_STRING_IMAGE_TO_TABLE = "Formbot";
var ID_RES_CONST_STRING_HELP_IMAGE_TO_TABLE = "新建样式帮助";

var ID_RES_CONST_MSG_ALERT_NO_SUPPORT_IN_LIST = "指定字头表格或段落编号模样的文段中无法使用该功能。";

var ID_RES_CONST_STRING_CANNOT_UPLOAD_FILE_TYPE = "file can not be uploaded. \ N * Available files:";
var ID_RES_CONST_STRING_CANNOT_READ_DOCUMENT_FORMAT = "Can not express form document format";
var ID_RES_CONST_STRING_NO_FILES_UPLOADED = "No files uploaded.";
var ID_RES_CONST_STRING_KEEP_ORG_HEIGHT = "Maintain original height";
var ID_RES_CONST_STRING_NEW_BLOCK_REFERENCE_HEIGHT = "New block is set to <br /> reference height";             //520
var ID_RES_CONST_STRING_BACKGROUND_COLOR = "Background color";
var ID_RES_CONST_STRING_LOSE_ALL_CONTINUE = "Your existing content will be initialized.\nDo you want to continue?";

var ID_RES_CONST_STRING_ENTER_SUBJECT = "Please enter the subject";
var ID_RES_CONST_STRING_ENTER_DETAIL = "Please enter the details.";

var ID_RES_CONST_STRING_TABLE_LOCK_EDIT_CELL = "Cell edit locked";
var ID_RES_CONST_STRING_NOT_EDITABLE_AREA = "This area is not editable.";

var ID_RES_PROP_TAG_STRING_TABLE_ID_CLASS_DEFINE = "Set ID / Class";
var ID_RES_PROP_TAG_STRING_TABLE_ID = "ID";
var ID_RES_PROP_TAG_STRING_TABLE_CLASS = "Class";
var ID_RES_DIALOG_ALERT_DUPLICATED_ID = "The ID being used.";

var ID_RES_DIALOG_CONFIRM_KEEP_PASTED_CONTENTS = "The editor default size is exceeded.\nDo you want to use the pasted file?";

var ID_RES_DIALOG_STRING_CUSTOM_INPUT_BOX = "Edit Input Form";
var ID_RES_DIALOG_STRING_TAG_NAME = "Tag Name";
var ID_RES_DIALOG_STRING_TAG_FORMAT = "Tag Format";
var ID_RES_DIALOG_STRING_CONTRACTOR_TYPE = "Contractor Type";
var ID_RES_DIALOG_STRING_TEXT_LENGTH = "Text Length";
var ID_RES_DIALOG_STRING_FONT_FAMILY = "Font Family";
var ID_RES_DIALOG_STRING_FONT_SIZE = "Font Size";
var ID_RES_DIALOG_STRING_FONT_WEIGHT = "Font Weight";
var ID_RES_DIALOG_STRING_READONLY = "Read only";

var ID_RES_CONST_EXTERNAL_DATA_AREA = "External data area";