/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// resource.js -	다국어 지원용 resource 모음(JAPAN)
//					
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


// 전체 적용되는 리소스 선언
var ID_RES_GLOBAL_DEFAULT_FONT_FAMILY = "Arial";
var ID_RES_GLOBAL_FONT_FAMILY_TYPE_1 = "Arial";

// ComboBox Size Layer(comboboxwin) 리소스 선언
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_8 = "あいうえ ABCD";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_24 = "あいう ABC";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_36 = "あい AB";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_MAX = "あい";
var ID_RES_COOMBOBOX_FONT_NAME_0 = "arial";
var ID_RES_COOMBOBOX_FONT_NAME_1 = "tahoma";
var ID_RES_COOMBOBOX_FONT_NAME_2 = "times new roman";
var ID_RES_COOMBOBOX_FONT_NAME_3 = "verdana";			//10
var ID_RES_COOMBOBOX_FONT_NAME_4 = "comic sans ms";
var ID_RES_COOMBOBOX_FONT_NAME_5 = "courier new";
var ID_RES_COOMBOBOX_FONT_NAME_6 = "";
var ID_RES_COOMBOBOX_FONT_NAME_7 = "";
var ID_RES_COOMBOBOX_FONT_NAME_8 = "";
var ID_RES_COOMBOBOX_FONT_NAME_9 = "";
var ID_RES_COOMBOBOX_FONT_NAME_10 = "";

// 글관련 서식 제거 문구 선언
var ID_RES_COMBOBOX_REMOVE_FONT_FAMILY = "基本";
var ID_RES_COMBOBOX_REMOVE_FONT_SIZE = "基本";
var ID_RES_COMBOBOX_REMOVE_LETTER_SPACING = "基本";		//20
var ID_RES_COMBOBOX_REMOVE_LINE_HEIGHT = "基本";

// 에디터 문자상수(initconst) 리소스 선언
var ID_RES_CONST_STRING_BOLD = "太字";
var ID_RES_CONST_STRING_ITALIC = "斜体";
var ID_RES_CONST_STRING_UNDERLINE = "下線";
var ID_RES_CONST_STRING_JUSTIFYLEFT = "左揃え";
var ID_RES_CONST_STRING_JUSTIFYCENTER = "中央揃え";
var ID_RES_CONST_STRING_JUSTIFYRIGHT = "右揃え";
var ID_RES_CONST_STRING_JUSTIFYJUSTIFY = "両側揃え";
var ID_RES_CONST_STRING_ORDERLIST = "番号付きリスト";
var ID_RES_CONST_STRING_UNORDERLIST = "記号付きリスト";	//30
var ID_RES_CONST_STRING_STRIKE = "取り消し線";
var ID_RES_CONST_STRING_SUBSCRIPT = "下付き文字";
var ID_RES_CONST_STRING_SUPERSCRIPT = "上付き文字";
var ID_RES_CONST_STRING_OUTDENT = "アウトデント";
var ID_RES_CONST_STRING_INDENT = "インデント";
var ID_RES_CONST_STRING_UNDO = "取り消し";
var ID_RES_CONST_STRING_REDO = "やり直し";
var ID_RES_CONST_STRING_FONT_NAME = "フォント";
var ID_RES_CONST_STRING_FONT_SIZE = "サイズ";
var ID_RES_CONST_STRING_FORE_COLOR = "前景色";			//40
var ID_RES_CONST_STRING_BACK_COLOR = "背景色";
var ID_RES_CONST_STRING_TABLE_CREATE = "表の生成";
var ID_RES_CONST_STRING_TABLE_ADD_ROW = "行の追加(Up)";
var ID_RES_CONST_STRING_TABLE_ADD_ROW_DOWN = "行の追加(Down)";
var ID_RES_CONST_STRING_TABLE_COPY_ROW_DOWN = "行の追加(Copy)";
var ID_RES_CONST_STRING_TABLE_DELETE_ROW = "行の削除";
var ID_RES_CONST_STRING_TABLE_ADD_COL = "列の追加(Left)";
var ID_RES_CONST_STRING_TABLE_ADD_COL_RIGHT = "列の追加(Right)";
var ID_RES_CONST_STRING_TABLE_DELETE_COL = "列の削除";
var ID_RES_CONST_STRING_TABLE_MERGE_CELL = "セルの結合";	//50
var ID_RES_CONST_STRING_TABLE_SPLIT_ROW = "行の分割";
var ID_RES_CONST_STRING_TABLE_SPLIT_COL = "列の分割";
var ID_RES_CONST_STRING_TABLE_SELECT = "選択";

var ID_RES_CONST_STRING_IMAGE_INSERT = "イメージ挿入/属性";
var ID_RES_CONST_STRING_FLASH_INSERT = "フラッシュ挿入/属性";
var ID_RES_CONST_STRING_MEDIA_INSERT = "動画挿入/属性";
var ID_RES_CONST_STRING_FULLSCREEN = "全画面";
var ID_RES_CONST_STRING_TABLE_CELL_PROPERTY = "セル属性";
var ID_RES_CONST_STRING_TABLE_PROPERTY = "テーブル属性";
var ID_RES_CONST_STRING_MARK_INSERT = "特殊文字挿入";						//60
var ID_RES_CONST_STRING_TABLE_TEMPLETE_INSERT = "表の生成（テンプレート)";


var ID_RES_CONST_STRING_ADJUST_HWP_BASIC = "HWP調整";
var ID_RES_CONST_STRING_ADJUST_DOC_BASIC = "Ｗord調整";
var ID_RES_CONST_STRING_HORIZONTAL_RULE = "水平線挿入";
var ID_RES_CONST_STRING_LETTER_SPACING = "文字間隔";
var ID_RES_CONST_STRING_LINE_HEIGHT = "行間隔";
var ID_RES_CONST_STRING_BODY_BG_COLOR = "文書の背景色";
var ID_RES_CONST_STRING_BODY_BG_IMAGE = "文書の背景イメージ";
var ID_RES_CONST_STRING_DOC_TEMPLETE = "編集ブロック挿入";
var ID_RES_CONST_STRING_PREVIEW = "プレビュー";								//70
var ID_RES_CONST_STRING_HIDE_MINIBAR = "ミニバー隠す";
var ID_RES_CONST_STRING_WRITE_AREA_SET = "編集領域の設定";
var ID_RES_CONST_STRING_SHOW_EDITABLE_AREA = "編集領域の表示";
var ID_RES_CONST_STRING_SAVEAS = "保存";
var ID_RES_CONST_STRING_PRINT = "出力";
var ID_RES_CONST_STRING_Z_INDEX_SETTING = "z-Indexの設定";
var ID_RES_CONST_STRING_TEXT_BOX = "テキストボックス";
var ID_RES_CONST_STRING_OBJECT_POSITION = "オブジェクトPosition設定";
var ID_RES_CONST_STRING_RESPONSIVE_WIDTH = "反応型の大きさ確認";
var ID_RES_CONST_STRING_DOC_LAYOUT = "レイアウト設定";							//80
var ID_RES_CONST_STRING_HEADING_SIZE = "スタイル";
var ID_RES_CONST_STRING_RESPONSIVE_SET = "反応型一括設定";
var ID_RES_CONST_STRING_FORM_TABLE = "表の編集ブロック";
var ID_RES_CONST_STRING_DRAW_TABLE = "表の作成";



//파일 메뉴 
var ID_RES_CONST_STRING_FILE_NEW				= "新規作成";
var ID_RES_CONST_STRING_FILE_OPEN				= "ファイルを開く";
var ID_RES_CONST_STRING_FILE_DOCFORM			= "書式様式";
var ID_RES_CONST_STRING_FILE_LAYOUT				= "レイアウト";

//편집 메뉴 
var ID_RES_CONST_STRING_CUT						= "カット";
var ID_RES_CONST_STRING_COPY					= "コピー";					//90
var ID_RES_CONST_STRING_PASTE					= "ペースト";
var ID_RES_CONST_STRING_EDIT_PASTESPECIAL		= "選んでつける";
var ID_RES_CONST_STRING_DELETE					= "削除";
var ID_RES_CONST_STRING_SELECT_ALL				= "すべて選択";
var ID_RES_CONST_STRING_EDIT_SEARCH				= "検索";
var ID_RES_CONST_STRING_EDIT_REPLACE			= "変換";
var ID_RES_CONST_STRING_REPLACE_CASE			= "大文字/小文字を変更する";

//보기 메뉴 
var ID_RES_CONST_STRING_VIEW_EDIT				= "編集窓";
var ID_RES_CONST_STRING_VIEW_HTML				= "ソース窓";

//삽입 메뉴 
var ID_RES_CONST_STRING_INSERT_IMAGE			= "イメージ";				//100
var ID_RES_CONST_STRING_INSERT_OBJECT			= "エンティティ";
var ID_RES_CONST_STRING_INSERT_SPECIALCHARS		= "特殊文字挿入";
var ID_RES_CONST_STRING_INSERT_BOOKMARK			= "ブックマーク";
var ID_RES_CONST_STRING_INSERT_EMOTICONS		= "絵文字";
var ID_RES_CONST_STRING_HYPERLINK_INSERT		= "ハイパーリンクの設定";
var ID_RES_CONST_STRING_HYPERLINK_MODIFY		= "ハイパーリンクの設定";
var ID_RES_CONST_STRING_HYPERLINK_REMOVE		= "ハイパーリンクの削除";

//서식 메뉴 
var ID_RES_CONST_STRING_STYLE_FONT				= "文字スタイル";
var ID_RES_CONST_STRING_STYLE_PARAGRAPH			= "段落スタイル";
var ID_RES_CONST_STRING_STYLE_STYLE				= "スタイル";					//110
var ID_RES_CONST_STRING_STYLE_UNORDEREDLIST		= "記号付きリスト";
var ID_RES_CONST_STRING_STYLE_ORDEREDLIST		= "番号付きリスト";
var ID_RES_CONST_STRING_STYLE_INCREASEORDER		= "レベル上げる";
var ID_RES_CONST_STRING_STYLE_DECREASEORDER		= "レベル下げる";

//표 메뉴 
var ID_RES_CONST_STRING_TABLE_CELL_STYLE		= "セルの枠/背景";
var ID_RES_CONST_STRING_TABLE_ADD_ROW_COL		= "行/間追加";
var ID_RES_CONST_STRING_TABLE_DELETE_ROW_COL	= "行/間削除";
var ID_RES_CONST_STRING_TABLE_SPLIT_CELL		= "セル分割";
var ID_RES_CONST_STRING_TABLE_CELL_SAME_HEIGHT	= "セルの高さを同じに";
var ID_RES_CONST_STRING_TABLE_CELL_SAME_WIDTH	= "セルの幅を同じに";				//120
var ID_RES_CONST_STRING_TABLE_CELL_ALIGN		= "セル整列";
var ID_RES_CONST_STRING_TABLE_MADANG			= "表庭";
var ID_RES_CONST_STRING_TABLE_FORMULA			= "計算式";
var ID_RES_CONST_STRING_TABLE_NUMBER_FORMAT		= "1,000単位の区分読点";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICALALIGN	= "セル縦整列";

var ID_RES_CONST_STRING_TABLE_BLOCK_FORMULA		= "ブロック計算式";
var ID_RES_CONST_STRING_TABLE_FORMULA			= "計算式";
var ID_RES_CONST_STRING_TABLE_SELECT_FORMULA	= "選択計算式";
var ID_RES_CONST_STRING_TABLE_EASY_FORMULA	= "簡単な計算式";

//도움말
var ID_RES_CONST_STRING_HELP_SHORTCUTS = "ショートカット";					//130
var ID_RES_CONST_STRING_HELP = "ヘルプ";
var ID_RES_CONST_STRING_PRODUCT_INFO = "バージョン情報";


//2depth 메뉴
var ID_RES_CONST_STRING_INSERT_OBJECT_MOVIE = "動画挿入";
var ID_RES_CONST_STRING_INSERT_OBJECT_FILE = "ファイル";
var ID_RES_CONST_STRING_INSERT_OBJECT_HR = "水平線挿入";

var ID_RES_CONST_STRING_STYLE_STYLE_BASIC = "基本";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT1 = "タイトル1";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT2 = "タイトル2";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT3 = "タイトル3";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT4 = "タイトル4";						//140
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT5 = "タイトル5";

var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_TOP = "上揃え";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_MIDDLE = "中央揃え";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_BOTTOM = "下に揃え";

var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTALALIGN	= "セルの横整列";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_LEFT = "左揃え";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_CENTER = "中央揃え";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_RIGHT = "右揃え";

var ID_RES_CONST_STRING_TABLE_BLOCK_SUM = "ブロック合計";
var ID_RES_CONST_STRING_TABLE_BLOCK_AVG = "ブロックの平均";							//150
var ID_RES_CONST_STRING_TABLE_BLOCK_MUL = "ブロック掛け";

var ID_RES_CONST_STRING_TABLE_HORIZONTAL_SUM = "横合計";
var ID_RES_CONST_STRING_TABLE_VERTICAL_SUM = "縦合計";
var ID_RES_CONST_STRING_TABLE_HORIZONTAL_AVERAGE = "横平均";
var ID_RES_CONST_STRING_TABLE_VERTICAL_AVERAGE = "縦平均";
var ID_RES_CONST_STRING_TABLE_HORIZONTAL_MULTIPLY = "横掛け";
var ID_RES_CONST_STRING_TABLE_VERTICAL_MULTIPLY = "縦掛け";

var ID_RES_CONST_STRING_TABLE_ADD_NUMBER_FORMAT = "定位点挿入";
var ID_RES_CONST_STRING_TABLE_REMOVE_NUMBER_FORMAT = "定位点削除";


//-- 툴바에만 존재하는 버튼
var ID_RES_CONST_STRING_STYLE_INCREASE_FONTSIZE = "フォントサイズ大きく";				//160
var ID_RES_CONST_STRING_STYLE_DECREASE_FONTSIZE = "フォントサイズ小さく";

// 폼태그 버튼
var ID_RES_CONST_STRING_FORM_TAG_SWITCH = "フォームコントロールの選択転換";
var ID_RES_CONST_STRING_FORM_TAG_CHECKBOX = "選択ボックス";
var ID_RES_CONST_STRING_FORM_TAG_SELECT = "リストボックス";

// 양식 템플릿
var ID_RES_CONST_STRING_TEMPLETE_FORM = "様式テンプレート";

// 빈문단삽입
var ID_RES_CONST_STRING_INSERT_PARAGRAPH_STARTPOINT = "スタートラインに文壇挿入";
var ID_RES_CONST_STRING_INSERT_PARAGRAPH_ENDPOINT = "最後のところに文壇挿入";

// 표 삭제
var ID_RES_CONST_STRING_TABLE_DELETE_TABLE = "テーブル 消す";

// 삽입 - 문단
var ID_RES_CONST_STRING_INSERT_PARAGRAPH = "文段";

// 서식 - 글자모양 - 보통모양 버튼 텍스트
var ID_RES_CONST_STRING_NORMAL = "普通の形";									//170

//표 - 표 텍스트로 변환
var ID_RES_CONST_STRING_TABLE_CONVERT_TEXT = "表をテキストに変換";

// 테이블생성 Layer(tablesize) 리소스 선언
var ID_RES_TABLE_SIZE_SELECT = "選択";
var ID_RES_TABLE_SIZE_CANCEL = "取り消し";

// 툴빌더(toolbuilder) 리소스 선언
var ID_RES_TOOL_STRING_MENU_FILE = "ファイル";
var ID_RES_TOOL_STRING_MENU_EDIT = "編集";
var ID_RES_TOOL_STRING_MENU_VIEW = "表示";
var ID_RES_TOOL_STRING_MENU_INSERT = "挿入";
var ID_RES_TOOL_STRING_MENU_BASIC = "書式";
var ID_RES_TOOL_STRING_MENU_TABLE = "表";
var ID_RES_TOOL_STRING_MENU_HELP = "ヘルプ";								//180
var ID_RES_TOOL_STRING_TAB_PREVIEW = "プレビュー";
var ID_RES_TOOL_STRING_TAB_EDIT = "編集窓";
var ID_RES_TOOL_STRING_TAB_SOURCE = "ソース窓";

// 사용자메세지(usermsg) 리소스 선언
var ID_RES_USER_MSG_STRING_ALERT_CUT = "ブラウザのセキュリティ設定では実行できません\nCtrl+X を押すと実行できます";
var ID_RES_USER_MSG_STRING_ALERT_COPY = "ブラウザのセキュリティ設定では実行できません\nCtrl+C を押すと実行できます";
var ID_RES_USER_MSG_STRING_ALERT_PASTE = "ブラウザのセキュリティ設定では実行できません\nCtrl+V を押すと実行できます";
var ID_RES_USER_MSG_STRING_WARNING_SCRIPT = "ソースコード上にスクリプトは含めません\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_MEDIA = "動画像挿入はIE6,7,8のみ支援されます\n";
var ID_RES_USER_MSG_STRING_WARNING_NO_IFRAME = "ソースコード上にiframeタグは含められません\n";
var ID_RES_USER_MSG_STRING_WARNING_NO_SOURCE_EDIT = "フォームのユーザーモードではソースウィンドウは使用できません\n";	//190
//var ID_RES_USER_MSG_STRING_WARNING_NO_FLASH_FF_2 = "firefox は3バージョン以上から支援されます\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_FLASH_FF_EDIT = "firefox 編集モードの設定上,支援されません\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_SUPPORT_FORM_MODE = "コード検査は様式管理者又は使用者モードでは支援されません\n";
//var ID_RES_USER_MSG_STRING_WARNING_INVALID_ATTIRIBUTE_CHARACTER = "属性値で＜,＞,＆,\',\"などは使用できません\n";
//var ID_RES_USER_MSG_STRING_WARNING_INVALID_COLOR_CODE = "유효한 색상코드를 입력하셔야 합니다.\n 예) #0099ff\n";
//var ID_RES_USER_MSG_STRING_WARNING_IN_CONTROL_KEY_NO_SOURCE_EDIT = "키보드 제어용에서는 소스창을 사용할 수 없습니다";

// 문서보정(leftviewui) 리소스 선언
var ID_RES_ADJUST_VIEW_CLOSE = "閉じる";

// 편집창 Title 리소스 선언
var ID_RES_EDIT_TITLE_STRING = "文章入力部分";

var ID_RES_PROP_BUILDER_BLOCK_PROP_ITEM_APPLY = "適用";

var ID_RES_CONST_STRING_ALIGN = "揃え";										//200

// 양식 저작(Form Table) 리소스 선언
var ID_RES_PROP_FORM_WIN_TITLE = "様式レイアウト";
var ID_RES_PROP_TAG_SELECT_WIN_TITLE = "リストボックス";
var ID_RES_PROP_MAPPING_CODE_WIN_TITLE = "様式コード";
var ID_RES_PROP_MAPPING_CSS_WIN_TITLE = "様式CSS設定";
var ID_RES_PROP_TEMPLETE_FORM_WIN_TITLE = "様式テンプレート";

// 컨텍스트 메뉴
var ID_RES_PROP_INSERT_IMAGE = "イメージ 属性";
var ID_RES_PROP_INSERT_FILE = "ファイル付け属性";

var ID_RES_DIALOG_BTN_OK = "確認";
var ID_RES_DIALOG_BTN_CANCEL = "取消";
var ID_RES_DIALOG_BTN_NOCOLOR = "色ない";										//210
var ID_RES_DIALOG_TAB_GENERAL = "一般";
var ID_RES_DIALOG_TAB_BORDER = "枠";
var ID_RES_DIALOG_TAB_BACKGROUND = "背景";
var ID_RES_DIALOG_FORM_LIST1 = "サンプル項目1";
var ID_RES_DIALOG_FORM_LIST2 = "サンプル項目2";
var ID_RES_DIALOG_FORM_LIST3 = "サンプル項目3";
var ID_RES_DIALOG_MAPPINGCODE_TAB1 = "電子決裁様式";
var ID_RES_DIALOG_MAPPINGCODE_TAB2 = "公文書様式";
var ID_RES_DIALOG_CONFIRM_SAVE = "<p>作成中の内容があります。</p><p>保存しますか?</p>";
var ID_RES_DIALOG_CONFIRM_YES = "はい";										//220
var ID_RES_DIALOG_CONFIRM_NO = "いいえ";
var ID_RES_DIALOG_CONFIRM_EMPTY_DOC = "文書が空いています。 ご確認ください。";
var ID_RES_DIALOG_ALERT_SELECTFILE = "ファイルを選択してください。";
var ID_RES_DIALOG_CONFIRM_FILE_DELETE_CONTENT = "ファイルを呼び込むと、作成中の内容が削除されます。\nファイルを呼び込みますか?";
var ID_RES_DIALOG_ALERT_ALLOWFILES = "ファイルはアップロードできません。\nアップロード可能ファイル";
var ID_RES_DIALOG_ALERT_SELECTIMAGE = "イメージファイルを選択した後、アップロードボタンをクリックしてください。";
var ID_RES_DIALOG_ALERT_SELECT_VALID_IMAGE = "正常なイメージを挿入してください。";
var ID_RES_DIALOG_ALERT_FIND_INPUT_TEXT = "探す内容を入力してください。";
var ID_RES_DIALOG_ALERT_FIND_ERROR = "検索中にエラーが発生しました。";
var ID_RES_DIALOG_ALERT_FIND_NOTHING = "該当内容を見つけられませんでした。";					//230
var ID_RES_DIALOG_CONFIRM_FIND_END = "文書の最後まで見つけました。\n文書を最初からずっと検索しますか。";
var ID_RES_DIALOG_CONFIRM_FIND_FIRST = "文書の最初まで見つけました。\n文書の最後までずっと検索しますか。";
var ID_RES_DIALOG_ALERT_REPLACE_INPUT_TEXT = "変更する内容を入力してください。";
var ID_RES_DIALOG_ALERT_REPLACE_ERROR = "変更進行中エラーが発生しました。";
var ID_RES_DIALOG_ALERT_REPLACEALL_COMPLETE = "すべて変更が完了しました。";
var ID_RES_DIALOG_ALERT_REPLACE_N = "個の項目が変更されました。";
var ID_RES_DIALOG_TITLE_FIND_REPLACE = "検索/変換";
var ID_RES_DIALOG_BTN_REPLACEALL = "全て変換";
var ID_RES_DIALOG_BTN_FIND_NEXT = "検索";
var ID_RES_DIALOG_TITLE_EXT_MOVIE = "外部動画";								//240
var ID_RES_DIALOG_TITLE_FILE_INSERT = "ファイル";
var ID_RES_DIALOG_BTN_INSERT = "挿入";
var ID_RES_DIALOG_TITLE_WEBEDITOR_INFO = "Douzone Web Editor 情報";

var ID_RES_DIALOG_LIST_TITLE_FORM_AREA = "様式領域";
var ID_RES_DIALOG_LIST_TITLE_FORM_SELECT = "様式の選択";
var ID_RES_DIALOG_ALERT_SELECT_DOCFORM = "書式の様式を選択してください。";
var ID_RES_DIALOG_CONFIRM_DOCFORM_DELETE_CONTENT = "書式様式を挿入すると、編集中の文書の内容が削除されます。\n挿入しますか。";
var ID_RES_DIALOG_ALERT_SELECT_LAYOUT_DESIGN = "レイアウトデザインを選択してください。";
var ID_RES_DIALOG_CONFIRM_LAYOUT_DELETE_CONTENT = "レアアウトを挿入すると、編集中の文書の内容が削除されます。\n挿入しますか。";

var ID_RES_DIALOG_STRING_FILE_PATH = "ファイルパス";						//250
var ID_RES_DIALOG_STRING_URL_INPUT = "挿入URL";	
var ID_RES_DIALOG_STRING_UPLOAD = "アップロード";
var ID_RES_DIALOG_STRING_SIZE = "サイズ";
var ID_RES_DIALOG_STRING_WIDTH = "幅";
var ID_RES_DIALOG_STRING_HEIGHT = "高さ";
var ID_RES_DIALOG_STRING_KEEP_RATIO = "比率維持";
var ID_RES_DIALOG_STRING_SET_ORG = "元のサイズを維持";
var ID_RES_DIALOG_STRING_MARGIN = "余白";
var ID_RES_DIALOG_STRING_MARGIN_LEFT = "左余白";
var ID_RES_DIALOG_STRING_MARGIN_TOP = "上余白";								//260
var ID_RES_DIALOG_STRING_MARGIN_RIGHT = "右余白";
var ID_RES_DIALOG_STRING_MARGIN_BOTTOM = "下余白";
var ID_RES_DIALOG_STRING_ALIGN_BASIC = "既定";
var ID_RES_DIALOG_STRING_ALIGN_LEFT = "左揃え";
var ID_RES_DIALOG_STRING_ALIGN_CENTER = "中央揃え";
var ID_RES_DIALOG_STRING_ALIGN_RIGHT = "右揃え";
var ID_RES_DIALOG_ALERT_MAX_VALUE = "最大値から外れました。\n最大値 : ";
var ID_RES_DIALOG_ALERT_MIN_VALUE = "最小値から外れました。\n最小値 : ";
var ID_RES_DIALOG_ALERT_NUMBER_ONLY = "数字のみ入力できます。";
var ID_RES_DIALOG_ALERT_SELECT_VALID_URL = "イメージURLをもう一度確認してください!";	//270
var ID_RES_DIALOG_ALERT_UPLOAD_ERROR = "アップロードしているうちにエラーが発生しました。 もう一度試してください。";
var ID_RES_DIALOG_ALERT_INSERT_IMAGE = "イメージを先に登録してください。";
var ID_RES_DIALOG_STRING_NO_STYLE_TEXT = "書式のないテキスト";
var ID_RES_DIALOG_STRING_HTML_STYLE_TEXT = "HTML 形式";
var ID_RES_DIALOG_STRING_FIND_TEXT = "探す内容";
var ID_RES_DIALOG_STRING_REPLACE_TEXT = "変換内容";
var ID_RES_DIALOG_STRING_FIND_OPTION = "検索オップション";
var ID_RES_DIALOG_STRING_CASESENSITIVE = "大/小文字区分";
var ID_RES_DIALOG_STRING_COMPLETEWORD = "単語単位で";
var ID_RES_DIALOG_STRING_IGNORESPACE = "分かち書き無視";							//280
var ID_RES_DIALOG_STRING_FIND_DERECTION = "検索方向";
var ID_RES_DIALOG_STRING_FIND_DOWN = "下で";
var ID_RES_DIALOG_STRING_FIND_UP = "上に";
var ID_RES_DIALOG_STRING_INPUT_SOURCE = "ソース入力";
var ID_RES_DIALOG_STRING_MOVIE_INPUT_GUIDE = "objectまたはiframeソースコード入力してください。";
var ID_RES_DIALOG_STRING_INPUT_MOVIE_SOURCE = "動画ソースを入力してください。";
var ID_RES_DIALOG_STRING_VIEW_TEXT = "表示するテキスト";
var ID_RES_DIALOG_ALERT_ALLOW_FORMAT = "フォーマットのみ提供します。";
var ID_RES_DIALOG_STRING_CHARACTER_AREA = "文字領域";
var ID_RES_DIALOG_STRING_CHARACTER_SELECT = "文字選択";						//290
var ID_RES_DIALOG_STRING_RECECT_USE_CHARACTER = "最近に使用した文字";

var ID_RES_DIALOG_ALERT_SELECT_CHARACTER = "文字を選択してください。";
var ID_RES_CONST_STRING_CHARACTER_GENERAL = "一般/記号";
var ID_RES_CONST_STRING_CHARACTER_ENG_NUMBER = "英語/数字";
var ID_RES_CONST_STRING_CHARACTER_GREEK = "ギリシャ語";
var ID_RES_CONST_STRING_CHARACTER_LINE = "線文字";
var ID_RES_CONST_STRING_CHARACTER_UNIT = "単位記号";
var ID_RES_CONST_STRING_CHARACTER_CIRCLE = "円文字";
var ID_RES_CONST_STRING_CHARACTER_BRAKETCHAR = "括弧文字";
var ID_RES_CONST_STRING_CHARACTER_FRACTION_SCRIPT = "分数/添字";				//300
var ID_RES_CONST_STRING_CHARACTER_ARROW = "矢印";
var ID_RES_CONST_STRING_CHARACTER_BRAKET = "括弧";
var ID_RES_CONST_STRING_CHARACTER_MATH = "数学演算";
var ID_RES_CONST_STRING_CHARACTER_PUNCTUATION_MARKS = "文章符号";
var ID_RES_CONST_STRING_CHARACTER_CURRENCY = "通貨記号";

var ID_RES_DIALOG_STRING_BOOKMARK_NAME = "ブックマーク名";
var ID_RES_DIALOG_STRING_BOOKMARK_LIST = "ブックマークリスト";
var ID_RES_DIALOG_STRING_MOVE = "移動";
var ID_RES_DIALOG_STRING_BOOKMARK_SORT_STANDARD = "ブックマーク整列基準";
var ID_RES_DIALOG_STRING_NAME = "名前";										//310
var ID_RES_DIALOG_STRING_POSITION = "位置";
var ID_RES_DIALOG_ALERT_INPUT_BOOKMARK_NAME = "しおりの名前を入力してください";
var ID_RES_DIALOG_ALERT_INPUT_SELECT_DELTE_BOOKMARK_ITEM = "ブックマークリストから削除する項目を選択してください";
var ID_RES_DIALOG_ALERT_INPUT_SELECT_MOVE_BOOKMARK_ITEM = "ブックマークリストで移動する項目を選択してください";

var ID_RES_DIALOG_STRING_LINK_TYPE = "リンク種類";
var ID_RES_DIALOG_STRING_WEB_ADDR = "ウェブアドレス";
var ID_RES_DIALOG_STRING_LINK_TARGET = "連結文書を開く";
var ID_RES_DIALOG_STRING_LINK_CURRENT_WINDOW = "同じウインドー";
var ID_RES_DIALOG_STRING_LINK_NEW_WINDOW = "新しいウィンドウに";
var ID_RES_DIALOG_STRING_LINK_NO_CONNECT = "連結しない";							//320
var ID_RES_DIALOG_STRING_LIST_SELECT = "選択";
var ID_RES_DIALOG_ALERT_SELECT_BOOKMARK = "ブックマークを選択してください";
var ID_RES_DIALOG_ALERT_INPUT_WEB_ADDR = "ウェブアドレスを入力してください";

var ID_RES_DIALOG_STRING_LETTERSPACING = "子癇";
var ID_RES_DIALOG_STRING_BASIC = "基本";
var ID_RES_DIALOG_STRING_PROPERTY = "属性";
var ID_RES_DIALOG_STRING_FONT_STYLE_PREVIEW = "あいうABCabc123※○";

var ID_RES_DIALOG_STRING_ALIGN_TYPE = "整列方式";
var ID_RES_DIALOG_STRING_NORMAL = "普通";
var ID_RES_DIALOG_STRING_SPACING = "間隔";									//330
var ID_RES_DIALOG_STRING_LINEHEIGHT = "行間隔";
var ID_RES_DIALOG_STRING_PARAGRAPH_TOP = "文壇の上";
var ID_RES_DIALOG_STRING_PARAGRAPH_BOTTOM = "文壇の下";
var ID_RES_DIALOG_STRING_FIRST_PARAGRAPH = "最初の行";

var ID_RES_DIALOG_STRING_NONE = "なし";
var ID_RES_DIALOG_STRING_VERSION = "バージョン";


var ID_RES_DIALOG_STRING_FORM_BASE_SIZE = "基準の大きさと高さ";
var ID_RES_DIALOG_STRING_FORM_HEIGHT_MSG = "高さ設定は<br/>様式生成際に反映される";
var ID_RES_DIALOG_STRING_FORM_OUTLINE = "外角線";
var ID_RES_DIALOG_STRING_FORM_TYPE = "タイプ";									//340
var ID_RES_DIALOG_STRING_FORM_COLOR = "色";
var ID_RES_DIALOG_STRING_FORM_MULTI_SELECT = "多重選択:<br/>&amp;nbsp;&amp;nbsp;Ctrlキー+オブジェクト選択";
var ID_RES_DIALOG_STRING_FORM_MULTI_OTHER_SELECT = "多重選択:<br/>&amp;nbsp;&amp;nbsp;オブジェクトの選択->shiftキー-><br/>&amp;nbsp;&amp;nbsp;他のオブジェクト選択";
var ID_RES_DIALOG_STRING_FORM_COPY_PASTE = "コピペ:<br/>&amp;nbsp;&amp;nbsp;オブジェクトを選択した後、Ctrlキー+V";
var ID_RES_DIALOG_STRING_FORM_COPY_MOVE = "移動:<br/>&amp;nbsp;&amp;nbsp;、上下左右の矢印キー";
var ID_RES_DIALOG_STRING_FORM_RESIZE = "大きさの調整:<br/>&amp;nbsp;&amp;nbsp;Ctrlキー+矢印キー";
var ID_RES_DIALOG_STRING_FORM_PRE_APPLY = "先に適用";
var ID_RES_DIALOG_ALERT_FORM_SIZE = "大きさ(width)単位が%である場合のみを提供しています。";

var ID_RES_PROP_TAG_STRING_ROW_NUM = "行数";
var ID_RES_PROP_TAG_STRING_COL_NUM = "列数";									//350
var ID_RES_PROP_TAG_STRING_ROW_COL = "行/セル";
var ID_RES_PROP_TAG_STRING_SIZE_DEFINE = "大きさ指定";
var ID_RES_PROP_TAG_STRING_WIDTH_UNIT = "幅単位";
var ID_RES_PROP_TAG_STRING_ALL_CELL_INNER_MARGIN = "すべてのセルの奥の余白";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN = "整列";

var ID_RES_PROP_TAG_STRING_TABLE_ALIGN_NONE = "ない";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN_LEFT = "左";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN_CENTER = "中";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN_RIGHT = "右";

var ID_RES_PROP_TAG_STRING_FILL = "満たす";									//360
var ID_RES_PROP_TAG_STRING_NO_COLOR_FILL = "色を満たすなし";
var ID_RES_PROP_TAG_STRING_COLOR = "色";
var ID_RES_PROP_TAG_STRING_FACE_COLOR = "面色";

var ID_RES_PROP_TAG_STRING_IMAGE = "イメージ";
var ID_RES_PROP_TAG_STRING_USER_IMAGE = "イメージ使用";
var ID_RES_PROP_TAG_STRING_IMAGE_FILE = "イメージファイル";
var ID_RES_PROP_TAG_STRING_FILL_TYPE = "満たすスタイル";
var ID_RES_PROP_TAG_STRING_REPEAT = "繰り返し";
var ID_RES_PROP_TAG_STRING_REPEAT_HOR = "横繰り返し";
var ID_RES_PROP_TAG_STRING_REPEAT_VER = "縦繰り返し";						//370
var ID_RES_PROP_TAG_STRING_REPEAT_NO = "繰り返しなし";

var ID_RES_PROP_TAG_LIST_NUM = "リスト数";
var ID_RES_PROP_TAG_LIST_CONTENT = "リスト内容";

var ID_RES_PROP_TAG_ADD_ROW = "行追加";
var ID_RES_PROP_TAG_UP = "アップ";
var ID_RES_PROP_TAG_DOWN = "ダウン";
var ID_RES_PROP_TAG_ADD_COL = "列の追加";

var ID_RES_PROP_TAG_SET_INNER_MARGIN = "奥の余白指定";

var ID_RES_PROP_TAG_STRING_LEFT = "左揃え";
var ID_RES_PROP_TAG_STRING_TOP = "アップ";									//380
var ID_RES_PROP_TAG_STRING_RIGHT = "右揃え";
var ID_RES_PROP_TAG_STRING_BOTTOM = "ダウン";

var ID_RES_PROP_TAG_STRING_ALIGN_HOR = "水平揃え";
var ID_RES_PROP_TAG_STRING_ALIGN_VER = "高さ 指定";
var ID_RES_PROP_TAG_STRING_ALIGN_TOP = "上揃え";
var ID_RES_PROP_TAG_STRING_ALIGN_MIDDLE = "中央揃え";
var ID_RES_PROP_TAG_STRING_ALIGN_BOTTOM = "下に揃え";

var ID_RES_PROP_TAG_STRING_APPLY_RANGE= "適用範囲";
var ID_RES_PROP_TAG_STRING_SELECTED_CELL = "選択されたセル";
var ID_RES_PROP_TAG_STRING_ALL_CELL = "すべてのセル";								//390

var ID_RES_PROP_TAG_ALERT_UNDER_100PER = "100%以下に設定してください。";

var ID_RES_PROP_TAG_STRING_SELECT_CELL_EDITOR = "適用するセルを編集画面で選択してください。";
var ID_RES_PROP_TAG_STRING_NO_CALC_SELECTED_CELL = "計算不可能な項目が選択されました。";
var ID_RES_PROP_TAG_STRING_SELECT_CELL = "セル選択";
var ID_RES_PROP_TAG_STRING_CALC_TYPE = "計算方法";
var ID_RES_PROP_TAG_STRING_CALC_SUM = "合計";
var ID_RES_PROP_TAG_STRING_CALC_AVG = "平均";
var ID_RES_PROP_TAG_STRING_CALC_MUL = "掛け";
var ID_RES_PROP_TAG_STRING_CALC_RESULT = "計算結果";
var ID_RES_PROP_TAG_STRING_SPLIT_ROW_COL = "行/間区分";						//400

var ID_RES_PROP_TEMPLETE_STRING_FORM_SUBJECT = "様式のタイトル";
var ID_RES_PROP_TEMPLETE_STRING_SUBJECT = "タイトル";
var ID_RES_PROP_TEMPLETE_STRING_SIZE_ITEM_SET = "大きさ/項目の設定";
var ID_RES_PROP_TEMPLETE_STRING_AUTO = "自動";
var ID_RES_PROP_ALERT_ONLY_NUMBER_CALC = "数字のみ計算が可能です。";

var ID_RES_DIALOG_SHORTCUTS_TITLE = "ショートカット";
var ID_RES_DIALOG_SHORTCUTS_MENU_PATH = "メニュー経路";
var ID_RES_DIALOG_SHORTCUTS_FUNCTION = "機能";
var ID_RES_DIALOG_SHORTCUTS_BASIC = "基本ホットキー";
var ID_RES_DIALOG_SHORTCUTS_SPACE = "空欄挿入";								//410
var ID_RES_DIALOG_SHORTCUTS_ENTER = "文壇の分け合い";
var ID_RES_DIALOG_SHORTCUTS_LEFT = "一字左に";
var ID_RES_DIALOG_SHORTCUTS_RIGHT = "一字右に";
var ID_RES_DIALOG_SHORTCUTS_DOWN = "一行下に";
var ID_RES_DIALOG_SHORTCUTS_UP = "一行の上に";
var ID_RES_DIALOG_SHORTCUTS_RIGHT_WORD = "一単語の右に";
var ID_RES_DIALOG_SHORTCUTS_LEFT_WORD = "一単語の左に";
var ID_RES_DIALOG_SHORTCUTS_DOWN_PARAGRAPH = "一段落の下に";
var ID_RES_DIALOG_SHORTCUTS_UP_PARAGRAPH = "一段落の上に";
var ID_RES_DIALOG_SHORTCUTS_HOME = "最初の行に";								//420
var ID_RES_DIALOG_SHORTCUTS_END = "最後の行に";
var ID_RES_DIALOG_SHORTCUTS_HOME_PAGE = "最初の画面に";
var ID_RES_DIALOG_SHORTCUTS_END_PAGE = "最後の画面に";
var ID_RES_DIALOG_SHORTCUTS_DELETE = "最後の文字を削除";
var ID_RES_DIALOG_SHORTCUTS_BACKSPACE = "頭文字を削除";
var ID_RES_DIALOG_SHORTCUTS_DELETE_WORD = "一単語を削除";
var ID_RES_DIALOG_SHORTCUTS_DELETE_PREV_WORD = "前の単語を削除";

var ID_RES_DIALOG_SHORTCUTS_FILE = "ファイルメニュー";
var ID_RES_DIALOG_SHORTCUTS_EDIT = "編集メニュー";
var ID_RES_DIALOG_SHORTCUTS_INSERT = "挿入メニュー";								//430
var ID_RES_DIALOG_SHORTCUTS_STYLE = "書式メニュー";
var ID_RES_DIALOG_SHORTCUTS_TABLE = "表メニュー";

var ID_RES_CONST_STRING_CLEAR = "オフ";

var ID_RES_CONST_STRING_INCREASE_LETTERSPACING = "子癇広く";
var ID_RES_CONST_STRING_DECREASE_LETTERSPACING = "子癇狭く";

var ID_RES_CONST_STRING_INCREASE_MARGIN_LEFT = "左側の余白増やす";
var ID_RES_CONST_STRING_DECREASE_MARGIN_LEFT = "左側の余白減らす";
var ID_RES_CONST_STRING_INCREASE_MARGIN_RIGHT = "右側の余白増やす";
var ID_RES_CONST_STRING_DECREASE_MARGIN_RIGHT = "右側の余白減らす";

var ID_RES_CONST_STRING_FIRST_PARAGRAPH_OUTDENT = "最初の行アウトデント";				//440
var ID_RES_CONST_STRING_FIRST_PARAGRAPH_INDENT = "最初の行インデント";

var ID_RES_CONST_STRING_INCREASE_LINEHEIGHT = "行間隔広く";
var ID_RES_CONST_STRING_DECREASE_LINEHEIGHT = "行間隔狭く";

var ID_RES_CONST_STRING_SELECT_CURRENT_CELL = "現在セル選択";
var ID_RES_CONST_STRING_MOVE_CELL_UNIT = "セル単位にカーソル移動";
var ID_RES_CONST_STRING_MOVE_NEXT_CELL = "表中で他のセルに移動(前進)";
var ID_RES_CONST_STRING_MOVE_PREV_CELL = "表中で他のセルに移動(逆方向)";

var ID_RES_CONST_STRING_BLOCK_ALL_COL = "間全体ブロック";
var ID_RES_CONST_STRING_BLOCK_ALL_ROW = "行全体ブロック";
var ID_RES_CONST_STRING_MULTI_CELL_SELECT = "多重セル選択時";					//450
var ID_RES_CONST_STRING_ARROW_KEY = "カーソルキー";

var ID_RES_CONST_STRING_STANDARD = "標準";
var ID_RES_CONST_STRING_USER_DEFINE = "カスタム";
var ID_RES_CONST_STRING_USER_SET = "カスタム";
var ID_RES_CONST_STRING_REPLACE_CASE_CAPITAL = "すべて大文字に変更する";
var ID_RES_CONST_STRING_REPLACE_CASE_SMALL = "すべて小文字に変更";
var ID_RES_CONST_STRING_REPLACE_CASE_REVERSE = "大文字・小文字変換";
var ID_RES_CONST_STRING_REPLACE_CASE_LETTER = "単語の先頭文字を大文字に";
var ID_RES_CONST_STRING_REPLACE_CASE_SENTENCE = "文章の最初の文字を大文字に";
var ID_RES_CONST_STRING_REPLACE_CASE_PARAGRAPH = "文壇の最初の文字を大文字に";			//460
var ID_RES_CONST_BTN_DELETE = "削除します";
var ID_RES_CONST_INSERT_IMAGE_PARAGRAPH_ALIGN = "本文整列";

var ID_RES_CONST_STRING_NEW_COLOR = "新しい色";
var ID_RES_CONST_STRING_CURRENT_COLOR = "現在色";
var ID_RES_CONST_STRING_OTHER_COLOR = "他の色";
var ID_RES_CONST_STRING_RECENT_COLOR = "最近使用した色";
var ID_RES_CONST_STRING_ADD_USER_COLOR = "ユーザーが指定した色に追加";
var ID_RES_CONST_STRING_RED = "赤";
var ID_RES_CONST_STRING_GREEN = "緑";
var ID_RES_CONST_STRING_BLUE = "青色";										//470
var ID_RES_CONST_STRING_HUE = "色";
var ID_RES_CONST_STRING_SATURATION = "彩度";
var ID_RES_CONST_STRING_LIGHTNESS = "明度";

var ID_RES_CONST_MSG_ALERT_NO_RECENT_COLOR = "最近使用した色がありません。";
var ID_RES_CONST_MSG_ALERT_DELETE_RECENT_COLOR = "最近使用した色をすべて削除しますか。";

var ID_RED_CONST_STRING_ALIGN_LEFT_TOP		= "左上";
var ID_RED_CONST_STRING_ALIGN_LEFT_MIDDLE	= "左の中間";
var ID_RED_CONST_STRING_ALIGN_LEFT_BOTTOM	= "左下";
var ID_RED_CONST_STRING_ALIGN_CENTER_TOP	= "上側の中央";
var ID_RED_CONST_STRING_ALIGN_CENTER_MIDDLE = "真ん中";						//480
var ID_RED_CONST_STRING_ALIGN_CENTER_BOTTOM = "下方の中央";
var ID_RED_CONST_STRING_ALIGN_RIGHT_TOP		= "右上";
var ID_RED_CONST_STRING_ALIGN_RIGHT_MIDDLE	= "右の中間";
var ID_RED_CONST_STRING_ALIGN_RIGHT_BOTTOM	= "右下";
var ID_RED_CONST_STRING_TABLE_CELL_BACKCOLOR	= "セル背景色";

var ID_RES_CONST_STRING_COLOR_STANDARD = "標準色";
var ID_RES_CONST_STRING_COLOR_THEME = "テーマ色";

var ID_RES_CONST_STRING_EMOTICONS_FEEL = "感情";
var ID_RES_CONST_STRING_EMOTICONS_ACTION = "行動";
var ID_RES_CONST_STRING_EMOTICONS_ETC = "その他の";								//490
var ID_RES_DIALOG_STRING_CATEGORY_AREA = "分類";
var ID_RES_DIALOG_STRING_EMOTICON_SELECT = "顔文字選択";
var ID_RES_DIALOG_STRING_RECECT_USE_EMOTICONS = "最近に使用した顔文字";

var ID_RES_UI_TOGGLE_STRING_RIBBON = "リボンメニュースタイル";
var ID_RES_UI_TOGGLE_STRING_TOOLBAR = "ツールバーのメニュースタイル";
var ID_RES_CONST_STRING_PRINT_PAGE_BREAK = "印刷ページの分割";
var ID_RES_CONST_STRING_VIEW_RULERBAR = "ルーラー表示";
var ID_RES_DIALOG_STRING_CASCADE_ORDERLIST = "多段階リスト";
var ID_RES_CONST_STRING_COPY_EXT_STYLE = "書式コピー";

var ID_RES_CONST_STRING_BORDER_TYPE = "枠タイプ";					//500
var ID_RES_CONST_STRING_BORDER_THICKNESS = "枠の厚さ";
var ID_RES_CONST_STRING_BORDER_COLOR = "枠の色";
var ID_RES_CONST_STRING_RESET_PICTURE = "Reset a picture";

var ID_RES_CONST_STRING_NO_LINE = "線無し";
var ID_RES_CONST_STRING_SOLID_LINE = "実線";
var ID_RES_CONST_STRING_DASHED_LINE = "波線";
var ID_RES_CONST_STRING_DOTTED_LINE = "点線";
var ID_RES_CONST_STRING_DOUBLE_LINE = "二重線";

var ID_RES_CONST_STRING_TABLE_SELECT_CELL = "セル選択";
var ID_RES_CONST_STRING_TABLE_SELECT_COL = "列選択";				//510
var ID_RES_CONST_STRING_TABLE_SELECT_ROW = "行選択";
var ID_RES_CONST_STRING_TABLE_SELECT_TABLE = "表選択";

var ID_RES_CONST_STRING_IMAGE_TO_TABLE = "Formbot";
var ID_RES_CONST_STRING_HELP_IMAGE_TO_TABLE = "様式抽出アドバイス";

var ID_RES_CONST_MSG_ALERT_NO_SUPPORT_IN_LIST = "グルモリ表や文壇番号のスタイルが指定された文壇には該当機能をサポートしません。";

var ID_RES_CONST_STRING_CANNOT_UPLOAD_FILE_TYPE = "file can not be uploaded. \ N * Available files:";
var ID_RES_CONST_STRING_CANNOT_READ_DOCUMENT_FORMAT = "Can not express form document format";
var ID_RES_CONST_STRING_NO_FILES_UPLOADED = "No files uploaded.";
var ID_RES_CONST_STRING_KEEP_ORG_HEIGHT = "Maintain original height";
var ID_RES_CONST_STRING_NEW_BLOCK_REFERENCE_HEIGHT = "New block is set to <br /> reference height";             //520
var ID_RES_CONST_STRING_BACKGROUND_COLOR = "Background color";
var ID_RES_CONST_STRING_LOSE_ALL_CONTINUE = "Your existing content will be initialized.\nDo you want to continue?";

var ID_RES_CONST_STRING_ENTER_SUBJECT = "Please enter the subject";
var ID_RES_CONST_STRING_ENTER_DETAIL = "Please enter the details.";

var ID_RES_CONST_STRING_TABLE_LOCK_EDIT_CELL = "Cell edit locked";
var ID_RES_CONST_STRING_NOT_EDITABLE_AREA = "This area is not editable.";

var ID_RES_PROP_TAG_STRING_TABLE_ID_CLASS_DEFINE = "Set ID / Class";
var ID_RES_PROP_TAG_STRING_TABLE_ID = "ID";
var ID_RES_PROP_TAG_STRING_TABLE_CLASS = "Class";
var ID_RES_DIALOG_ALERT_DUPLICATED_ID = "The ID being used.";

var ID_RES_DIALOG_CONFIRM_KEEP_PASTED_CONTENTS = "The editor default size is exceeded.\nDo you want to use the pasted file?";

var ID_RES_DIALOG_STRING_CUSTOM_INPUT_BOX = "Edit Input Form";
var ID_RES_DIALOG_STRING_TAG_NAME = "Tag Name";
var ID_RES_DIALOG_STRING_TAG_FORMAT = "Tag Format";
var ID_RES_DIALOG_STRING_CONTRACTOR_TYPE = "Contractor Type";
var ID_RES_DIALOG_STRING_TEXT_LENGTH = "Text Length";
var ID_RES_DIALOG_STRING_FONT_FAMILY = "Font Family";
var ID_RES_DIALOG_STRING_FONT_SIZE = "Font Size";
var ID_RES_DIALOG_STRING_FONT_WEIGHT = "Font Weight";
var ID_RES_DIALOG_STRING_READONLY = "Read only";

var ID_RES_CONST_EXTERNAL_DATA_AREA = "External data area";