/* 단축키 안내 */
var shortcutsInfo = "";
shortcutsInfo += "<table width='' border='1' style='border-collapse:collapse;border:1px solid #a0a0a0;' cellpadding='0' cellspacing='0'>";

shortcutsInfo += "<tr>";
shortcutsInfo += "<td width='130' class='dze_shortcuts_table_head'>"+ID_RES_DIALOG_SHORTCUTS_TITLE+"</td>";
shortcutsInfo += "<td width='190' class='dze_shortcuts_table_head'>"+ID_RES_DIALOG_SHORTCUTS_MENU_PATH+"</td>";
shortcutsInfo += "<td width='190' class='dze_shortcuts_table_head'>"+ID_RES_DIALOG_SHORTCUTS_FUNCTION+"</td>";
shortcutsInfo += "</tr>";


shortcutsInfo += "<tr><td colspan='3' class='dze_shortcuts_table_title'>"+ID_RES_DIALOG_SHORTCUTS_BASIC+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>SpaceBar</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_SPACE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Enter</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_ENTER+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>←</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_LEFT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>→</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_RIGHT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>↓</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_DOWN+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>↑</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_UP+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+→</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_RIGHT_WORD+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+←</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_LEFT_WORD+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+↓</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_DOWN_PARAGRAPH+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+↑</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_UP_PARAGRAPH+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Home</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_HOME+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>End</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_END+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Home</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_HOME_PAGE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+End</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_END_PAGE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Delete</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_DELETE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>BackSpace</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_BACKSPACE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Delete</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_DELETE_WORD+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+BackSpace</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_DIALOG_SHORTCUTS_DELETE_PREV_WORD+"</td></tr>";

shortcutsInfo += "<tr><td colspan='3' class='dze_shortcuts_table_title'>"+ID_RES_DIALOG_SHORTCUTS_FILE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+N</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_FILE+" - "+ID_RES_CONST_STRING_FILE_NEW+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_FILE_NEW+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+O</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_FILE+" - "+ID_RES_CONST_STRING_FILE_OPEN+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_FILE_OPEN+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+S / Ctrl+S</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_FILE+" - "+ID_RES_CONST_STRING_SAVEAS+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_SAVEAS+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+P</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_FILE+" - "+ID_RES_CONST_STRING_PRINT+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_PRINT+"</td></tr>";

shortcutsInfo += "<tr><td colspan='3' class='dze_shortcuts_table_title'>"+ID_RES_DIALOG_SHORTCUTS_EDIT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Z</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_EDIT+" - "+ID_RES_CONST_STRING_UNDO+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_UNDO+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+Z</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_EDIT+" - "+ID_RES_CONST_STRING_REDO+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_REDO+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+X / Shift+Delete</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_EDIT+" - "+ID_RES_CONST_STRING_CUT+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_CUT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+C / Ctrl+Insert</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_EDIT+" - "+ID_RES_CONST_STRING_COPY+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_COPY+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+V / Shift+Insert</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_EDIT+" - "+ID_RES_CONST_STRING_PASTE+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_PASTE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Alt+V</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_EDIT+" - "+ID_RES_CONST_STRING_EDIT_PASTESPECIAL+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_EDIT_PASTESPECIAL+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+E</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_EDIT+" - "+ID_RES_CONST_STRING_DELETE+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_DELETE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+A</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_EDIT+" - "+ID_RES_CONST_STRING_SELECT_ALL+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_SELECT_ALL+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Q,F / Ctrl+F</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_EDIT+" - "+ID_RES_CONST_STRING_EDIT_SEARCH+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_EDIT_SEARCH+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Q,A / Ctrl+H</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_EDIT+" - "+ID_RES_CONST_STRING_EDIT_REPLACE+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_EDIT_REPLACE+"</td></tr>";

shortcutsInfo += "<tr><td colspan='3' class='dze_shortcuts_table_title'>"+ID_RES_DIALOG_SHORTCUTS_INSERT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+F10</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_INSERT+" - "+ID_RES_CONST_STRING_INSERT_SPECIALCHARS+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_INSERT_SPECIALCHARS+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+K,B</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_INSERT+" - "+ID_RES_CONST_STRING_INSERT_BOOKMARK+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_INSERT_BOOKMARK+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+K,H</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_INSERT+" - "+ID_RES_CONST_STRING_HYPERLINK_INSERT+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_HYPERLINK_INSERT+"</td></tr>";

shortcutsInfo += "<tr><td colspan='3' class='dze_shortcuts_table_title'>"+ID_RES_DIALOG_SHORTCUTS_STYLE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+L</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_FONT+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_STYLE_FONT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+W</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_PARAGRAPH+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_STYLE_PARAGRAPH+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+[</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_ORDERLIST+" "+ID_RES_PROP_BUILDER_BLOCK_PROP_ITEM_APPLY+"/"+ID_RES_CONST_STRING_CLEAR+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_ORDERLIST+" "+ID_RES_PROP_BUILDER_BLOCK_PROP_ITEM_APPLY+"/"+ID_RES_CONST_STRING_CLEAR+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+]</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_UNORDERLIST+" "+ID_RES_PROP_BUILDER_BLOCK_PROP_ITEM_APPLY+"/"+ID_RES_CONST_STRING_CLEAR+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_UNORDERLIST+" "+ID_RES_PROP_BUILDER_BLOCK_PROP_ITEM_APPLY+"/"+ID_RES_CONST_STRING_CLEAR+"</td></tr>";
//shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+←</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_INCREASEORDER+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_STYLE_INCREASEORDER+"</td></tr>";
//shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+→</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_DECREASEORDER+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_STYLE_DECREASEORDER+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+Shift+E / Ctrl+]</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_FONT+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_STYLE_INCREASE_FONTSIZE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+Shift+R / Ctrl+[</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_FONT+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_STYLE_DECREASE_FONTSIZE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+Shift+W</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_FONT+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_INCREASE_LETTERSPACING+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+Shift+N</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_FONT+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_DECREASE_LETTERSPACING+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+Shift+U / Ctrl+U</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_FONT+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_UNDERLINE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+Shift+B / Ctrl+B</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_FONT+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_BOLD+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+Shift+I / Ctrl+I</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_FONT+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_ITALIC+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+Shift+P</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_FONT+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_SUPERSCRIPT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+Shift+S</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_FONT+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_SUBSCRIPT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Alt+A</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_FONT+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_SUPERSCRIPT+"/"+ID_RES_CONST_STRING_SUBSCRIPT+"/"+ID_RES_DIALOG_STRING_NORMAL+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Alt+5</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_PARAGRAPH+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_DECREASE_MARGIN_LEFT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Alt+6</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_PARAGRAPH+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_INCREASE_MARGIN_LEFT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Alt+7</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_PARAGRAPH+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_INCREASE_MARGIN_RIGHT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Alt+8</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_PARAGRAPH+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_DECREASE_MARGIN_RIGHT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+F5 / Ctrl+Shift+O</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_PARAGRAPH+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_FIRST_PARAGRAPH_OUTDENT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+F6 / Ctrl+Shift+I</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_PARAGRAPH+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_FIRST_PARAGRAPH_INDENT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+Shift+Z </td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_PARAGRAPH+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_INCREASE_LINEHEIGHT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+Shift+A </td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_PARAGRAPH+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_DECREASE_LINEHEIGHT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+M</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_PARAGRAPH+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_JUSTIFYJUSTIFY+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+L</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_PARAGRAPH+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_JUSTIFYLEFT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+R</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_PARAGRAPH+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_JUSTIFYRIGHT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+C</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_BASIC+" - "+ID_RES_CONST_STRING_STYLE_PARAGRAPH+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_JUSTIFYCENTER+"</td></tr>";


shortcutsInfo += "<tr><td colspan='3' class='dze_shortcuts_table_title'>"+ID_RES_DIALOG_SHORTCUTS_TABLE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Shift+F5</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_SELECT_CURRENT_CELL+"</td></tr>";
//shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+"+ID_RES_CONST_STRING_ARROW_KEY+"</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_MOVE_CELL_UNIT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Enter</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_PROP_TAG_ADD_ROW+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+BackSpace</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_DELETE_ROW+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Tab</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_MOVE_NEXT_CELL+"</td></tr>";
//shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Shift+Tab</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_MOVE_PREV_CELL+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+Insert</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_TABLE+" - "+ID_RES_CONST_STRING_TABLE_ADD_ROW_COL+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_ADD_ROW_COL+"</td></tr>";
//shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Alt+Delete</td><td class='dze_shortcuts_table_body'>"+ID_RES_TOOL_STRING_MENU_TABLE+" - "+ID_RES_CONST_STRING_TABLE_DELETE_ROW_COL+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_DELETE_ROW_COL+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+H</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_EASY_FORMULA+" - "+ID_RES_CONST_STRING_TABLE_HORIZONTAL_SUM+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_HORIZONTAL_SUM+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+V</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_EASY_FORMULA+" - "+ID_RES_CONST_STRING_TABLE_VERTICAL_SUM+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_VERTICAL_SUM+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+J</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_EASY_FORMULA+" - "+ID_RES_CONST_STRING_TABLE_HORIZONTAL_AVERAGE+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_HORIZONTAL_AVERAGE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+B</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_EASY_FORMULA+" - "+ID_RES_CONST_STRING_TABLE_VERTICAL_AVERAGE+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_VERTICAL_AVERAGE+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+K</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_EASY_FORMULA+" - "+ID_RES_CONST_STRING_TABLE_HORIZONTAL_MULTIPLY+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_HORIZONTAL_MULTIPLY+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Shift+G</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_EASY_FORMULA+" - "+ID_RES_CONST_STRING_TABLE_VERTICAL_MULTIPLY+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_VERTICAL_MULTIPLY+"</td></tr>";
//shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>F7</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_BLOCK_ALL_COL+"</td></tr>";
//shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>F8</td><td class='dze_shortcuts_table_body'>-</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_BLOCK_ALL_ROW+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Alt+H</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_CELL_SAME_HEIGHT+" ("+ID_RES_CONST_STRING_MULTI_CELL_SELECT+")</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_CELL_SAME_HEIGHT+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Alt+W</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_CELL_SAME_WIDTH+" ("+ID_RES_CONST_STRING_MULTI_CELL_SELECT+")</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_CELL_SAME_WIDTH+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Alt+M</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_MERGE_CELL+" ("+ID_RES_CONST_STRING_MULTI_CELL_SELECT+")</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_MERGE_CELL+"</td></tr>";
shortcutsInfo += "<tr><td class='dze_shortcuts_table_body'>Ctrl+Alt+S</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_SPLIT_CELL+"</td><td class='dze_shortcuts_table_body'>"+ID_RES_CONST_STRING_TABLE_SPLIT_CELL+"</td></tr>";


shortcutsInfo += "</table>";