/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// resource.js -	다국어 지원용 resource 모음(KOREAN)
//					
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


// 전체 적용되는 리소스 선언
var ID_RES_GLOBAL_DEFAULT_FONT_FAMILY = "굴림";				//1
var ID_RES_GLOBAL_FONT_FAMILY_TYPE_1 = "돋움";

// ComboBox Size Layer(comboboxwin) 리소스 선언
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_8 = "가나다라 ABCD";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_24 = "가나다 ABC";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_36 = "가나 AB";			//5
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_MAX = "가나";
var ID_RES_COOMBOBOX_FONT_NAME_0 = "돋움";
var ID_RES_COOMBOBOX_FONT_NAME_1 = "돋움체";
var ID_RES_COOMBOBOX_FONT_NAME_2 = "굴림";
var ID_RES_COOMBOBOX_FONT_NAME_3 = "굴림체";					//10
var ID_RES_COOMBOBOX_FONT_NAME_4 = "바탕";
var ID_RES_COOMBOBOX_FONT_NAME_5 = "바탕체";
var ID_RES_COOMBOBOX_FONT_NAME_6 = "궁서";
var ID_RES_COOMBOBOX_FONT_NAME_7 = "맑은 고딕";
var ID_RES_COOMBOBOX_FONT_NAME_8 = "arial";					//15
var ID_RES_COOMBOBOX_FONT_NAME_9 = "tahoma";
var ID_RES_COOMBOBOX_FONT_NAME_10 = "times new roman";

// 글관련 서식 제거 문구 선언
var ID_RES_COMBOBOX_REMOVE_FONT_FAMILY = "기본";
var ID_RES_COMBOBOX_REMOVE_FONT_SIZE = "기본";
var ID_RES_COMBOBOX_REMOVE_LETTER_SPACING = "기본";			//20
var ID_RES_COMBOBOX_REMOVE_LINE_HEIGHT = "기본";

// 에디터 문자상수(initconst) 리소스 선언
var ID_RES_CONST_STRING_BOLD = "굵게";
var ID_RES_CONST_STRING_ITALIC = "기울림꼴";
var ID_RES_CONST_STRING_UNDERLINE = "밑줄";
var ID_RES_CONST_STRING_JUSTIFYLEFT = "왼쪽 맞춤";				//25
var ID_RES_CONST_STRING_JUSTIFYCENTER = "가운데 맞춤";
var ID_RES_CONST_STRING_JUSTIFYRIGHT = "오른쪽 맞춤";
var ID_RES_CONST_STRING_JUSTIFYJUSTIFY = "양쪽 맞춤";
var ID_RES_CONST_STRING_ORDERLIST = "문단 번호 모양";
var ID_RES_CONST_STRING_UNORDERLIST = "글머리표 모양";			//30
var ID_RES_CONST_STRING_STRIKE = "취소선";
var ID_RES_CONST_STRING_SUBSCRIPT = "아래 첨자";
var ID_RES_CONST_STRING_SUPERSCRIPT = "위 첨자";
var ID_RES_CONST_STRING_OUTDENT = "내어쓰기";
var ID_RES_CONST_STRING_INDENT = "들여쓰기";					//35
var ID_RES_CONST_STRING_UNDO = "되돌리기";
var ID_RES_CONST_STRING_REDO = "다시하기";
var ID_RES_CONST_STRING_FONT_NAME = "글꼴 종류";
var ID_RES_CONST_STRING_FONT_SIZE = "글꼴 크기";
var ID_RES_CONST_STRING_FORE_COLOR = "글자색";					//40
var ID_RES_CONST_STRING_BACK_COLOR = "글자 배경색";		
var ID_RES_CONST_STRING_TABLE_CREATE = "표 만들기";
var ID_RES_CONST_STRING_TABLE_ADD_ROW = "위쪽에 줄 추가하기";
var ID_RES_CONST_STRING_TABLE_ADD_ROW_DOWN = "아래쪽에 줄 추가하기";
var ID_RES_CONST_STRING_TABLE_COPY_ROW_DOWN = "행 추가(복사)";	//45
var ID_RES_CONST_STRING_TABLE_DELETE_ROW = "줄 지우기";
var ID_RES_CONST_STRING_TABLE_ADD_COL = "왼쪽에 칸 추가하기";
var ID_RES_CONST_STRING_TABLE_ADD_COL_RIGHT = "오른쪽에 칸 추가하기";
var ID_RES_CONST_STRING_TABLE_DELETE_COL = "칸 지우기";
var ID_RES_CONST_STRING_TABLE_MERGE_CELL = "셀 합치기";			//50
var ID_RES_CONST_STRING_TABLE_SPLIT_ROW = "행 분할";
var ID_RES_CONST_STRING_TABLE_SPLIT_COL = "열 분할";
var ID_RES_CONST_STRING_TABLE_SELECT = "선택";

var ID_RES_CONST_STRING_IMAGE_INSERT = "이미지 삽입/속성";
var ID_RES_CONST_STRING_FLASH_INSERT = "플래시 삽입/속성";		//55
var ID_RES_CONST_STRING_MEDIA_INSERT = "동영상 삽입/속성";
var ID_RES_CONST_STRING_FULLSCREEN = "전체화면";
var ID_RES_CONST_STRING_TABLE_CELL_PROPERTY = "셀 속성";
var ID_RES_CONST_STRING_TABLE_PROPERTY = "표 속성";
var ID_RES_CONST_STRING_MARK_INSERT = "특수문자 삽입";			//60
var ID_RES_CONST_STRING_TABLE_TEMPLETE_INSERT = "표 생성(템플릿)";


var ID_RES_CONST_STRING_ADJUST_HWP_BASIC = "한글보정";
var ID_RES_CONST_STRING_ADJUST_DOC_BASIC = "워드보정";
var ID_RES_CONST_STRING_HORIZONTAL_RULE = "수평선 삽입";
var ID_RES_CONST_STRING_LETTER_SPACING = "글간격";				//65
var ID_RES_CONST_STRING_LINE_HEIGHT = "줄간격";
var ID_RES_CONST_STRING_BODY_BG_COLOR = "문서 배경색";
var ID_RES_CONST_STRING_BODY_BG_IMAGE = "문서 배경이미지";
var ID_RES_CONST_STRING_DOC_TEMPLETE = "편집블럭 삽입";
var ID_RES_CONST_STRING_PREVIEW = "미리보기";					//70
var ID_RES_CONST_STRING_HIDE_MINIBAR = "미니바 숨기기";
var ID_RES_CONST_STRING_WRITE_AREA_SET = "편집영역 설정";
var ID_RES_CONST_STRING_SHOW_EDITABLE_AREA = "편집영역 보이기";
var ID_RES_CONST_STRING_SAVEAS = "저장하기";
var ID_RES_CONST_STRING_PRINT = "인쇄";						//75
var ID_RES_CONST_STRING_Z_INDEX_SETTING = "z-Index 설정";
var ID_RES_CONST_STRING_TEXT_BOX = "글상자";
var ID_RES_CONST_STRING_OBJECT_POSITION = "객체 Position 설정";
var ID_RES_CONST_STRING_RESPONSIVE_WIDTH = "반응형 크기 확인";
var ID_RES_CONST_STRING_DOC_LAYOUT = "레이아웃 설정";			//80
var ID_RES_CONST_STRING_HEADING_SIZE = "스타일";
var ID_RES_CONST_STRING_RESPONSIVE_SET = "반응형 일괄설정";
var ID_RES_CONST_STRING_FORM_TABLE = "표 편집블럭"
var ID_RES_CONST_STRING_DRAW_TABLE = "표 그리기"



//파일 메뉴 
var ID_RES_CONST_STRING_FILE_NEW				= "새 문서";	//85
var ID_RES_CONST_STRING_FILE_OPEN				= "불러오기";
var ID_RES_CONST_STRING_FILE_DOCFORM			= "서식 양식";
var ID_RES_CONST_STRING_FILE_LAYOUT				= "레이아웃";

//편집 메뉴 
var ID_RES_CONST_STRING_CUT						= "오려두기";
var ID_RES_CONST_STRING_COPY					= "복사하기";	//90
var ID_RES_CONST_STRING_PASTE					= "붙이기";
var ID_RES_CONST_STRING_EDIT_PASTESPECIAL		= "골라 붙이기";
var ID_RES_CONST_STRING_DELETE					= "지우기";
var ID_RES_CONST_STRING_SELECT_ALL				= "전체 선택";
var ID_RES_CONST_STRING_EDIT_SEARCH				= "찾기";		//95
var ID_RES_CONST_STRING_EDIT_REPLACE			= "바꾸기";
var ID_RES_CONST_STRING_REPLACE_CASE			= "대/소문자 바꾸기";

//보기 메뉴 
var ID_RES_CONST_STRING_VIEW_EDIT				= "편집 보기";
var ID_RES_CONST_STRING_VIEW_HTML				= "HTML 보기";

//삽입 메뉴 
var ID_RES_CONST_STRING_INSERT_IMAGE			= "그림";		//100
var ID_RES_CONST_STRING_INSERT_OBJECT			= "개체";
var ID_RES_CONST_STRING_INSERT_SPECIALCHARS		= "문자표";
var ID_RES_CONST_STRING_INSERT_EMOTICONS		= "이모티콘";
var ID_RES_CONST_STRING_INSERT_BOOKMARK			= "책갈피";
var ID_RES_CONST_STRING_HYPERLINK_INSERT		= "하이퍼링크";			//105
var ID_RES_CONST_STRING_HYPERLINK_MODIFY		= "하이퍼링크 고치기";
var ID_RES_CONST_STRING_HYPERLINK_REMOVE		= "하이퍼링크 지우기";

//서식 메뉴 
var ID_RES_CONST_STRING_STYLE_FONT				= "글자모양";
var ID_RES_CONST_STRING_STYLE_PARAGRAPH			= "문단모양";
var ID_RES_CONST_STRING_STYLE_STYLE				= "스타일";			//110
var ID_RES_CONST_STRING_STYLE_UNORDEREDLIST		= "글머리표 모양";
var ID_RES_CONST_STRING_STYLE_ORDEREDLIST		= "문단번호 모양";
var ID_RES_CONST_STRING_STYLE_INCREASEORDER		= "한 수준 증가";
var ID_RES_CONST_STRING_STYLE_DECREASEORDER		= "한 수준 감소";

//표 메뉴 
var ID_RES_CONST_STRING_TABLE_CELL_STYLE		= "셀 테두리/배경";		//115
var ID_RES_CONST_STRING_TABLE_ADD_ROW_COL		= "줄/칸 추가하기";
var ID_RES_CONST_STRING_TABLE_DELETE_ROW_COL	= "줄/칸 지우기";
var ID_RES_CONST_STRING_TABLE_SPLIT_CELL		= "셀 나누기";
var ID_RES_CONST_STRING_TABLE_CELL_SAME_HEIGHT	= "셀 높이를 같게";
var ID_RES_CONST_STRING_TABLE_CELL_SAME_WIDTH	= "셀 너비를 같게";		//120
var ID_RES_CONST_STRING_TABLE_CELL_ALIGN		= "셀 정렬";
var ID_RES_CONST_STRING_TABLE_MADANG			= "표 마당";
var ID_RES_CONST_STRING_TABLE_FORMULA			= "계산식";
var ID_RES_CONST_STRING_TABLE_NUMBER_FORMAT		= "1,000단위 구분쉼표";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICALALIGN	= "셀 세로 정렬";	//125

var ID_RES_CONST_STRING_TABLE_BLOCK_FORMULA		= "블록 계산식";
var ID_RES_CONST_STRING_TABLE_FORMULA			= "계산식";
var ID_RES_CONST_STRING_TABLE_SELECT_FORMULA	= "선택 계산식";
var ID_RES_CONST_STRING_TABLE_EASY_FORMULA	= "쉬운 계산식";

//도움말
var ID_RES_CONST_STRING_HELP_SHORTCUTS = "단축키 도움말";				//130
var ID_RES_CONST_STRING_HELP = "제품 도움말";
var ID_RES_CONST_STRING_PRODUCT_INFO = "제품 정보";


//2depth 메뉴
var ID_RES_CONST_STRING_INSERT_OBJECT_MOVIE = "동영상";
var ID_RES_CONST_STRING_INSERT_OBJECT_FILE = "파일";
var ID_RES_CONST_STRING_INSERT_OBJECT_HR = "문단띠";					//135

var ID_RES_CONST_STRING_STYLE_STYLE_BASIC = "기본";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT1 = "제목1";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT2 = "제목2";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT3 = "제목3";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT4 = "제목4";				//140
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT5 = "제목5";

var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_TOP = "위쪽 정렬";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_MIDDLE = "가운데 정렬";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_BOTTOM = "아래쪽 정렬";

var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTALALIGN	= "셀 가로 정렬";	//145
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_LEFT = "왼쪽 정렬";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_CENTER = "가운데 정렬";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_RIGHT = "오른쪽 정렬";

var ID_RES_CONST_STRING_TABLE_BLOCK_SUM = "블록 합계";
var ID_RES_CONST_STRING_TABLE_BLOCK_AVG = "블록 평균";					//150
var ID_RES_CONST_STRING_TABLE_BLOCK_MUL = "블록 곱";

var ID_RES_CONST_STRING_TABLE_HORIZONTAL_SUM = "가로 합계";
var ID_RES_CONST_STRING_TABLE_VERTICAL_SUM = "세로 합계";
var ID_RES_CONST_STRING_TABLE_HORIZONTAL_AVERAGE = "가로 평균";
var ID_RES_CONST_STRING_TABLE_VERTICAL_AVERAGE = "세로 평균";			//155
var ID_RES_CONST_STRING_TABLE_HORIZONTAL_MULTIPLY = "가로 곱";
var ID_RES_CONST_STRING_TABLE_VERTICAL_MULTIPLY = "세로 곱";

var ID_RES_CONST_STRING_TABLE_ADD_NUMBER_FORMAT = "자릿점 넣기";
var ID_RES_CONST_STRING_TABLE_REMOVE_NUMBER_FORMAT = "자릿점 빼기";


//-- 툴바에만 존재하는 버튼
var ID_RES_CONST_STRING_STYLE_INCREASE_FONTSIZE = "글꼴 크기 크게";		//160
var ID_RES_CONST_STRING_STYLE_DECREASE_FONTSIZE = "글꼴 크기 작게";

// 폼태그 버튼
var ID_RES_CONST_STRING_FORM_TAG_SWITCH = "폼 컨트롤 선택전환";
var ID_RES_CONST_STRING_FORM_TAG_CHECKBOX = "선택상자";
var ID_RES_CONST_STRING_FORM_TAG_SELECT = "목록상자";

// 양식 템플릿
var ID_RES_CONST_STRING_TEMPLETE_FORM = "양식 템플릿";					//165

// 빈문단삽입
var ID_RES_CONST_STRING_INSERT_PARAGRAPH_STARTPOINT = "시작점 문단삽입";
var ID_RES_CONST_STRING_INSERT_PARAGRAPH_ENDPOINT = "끝지점 문단삽입";

// 표 삭제
var ID_RES_CONST_STRING_TABLE_DELETE_TABLE = "표 지우기";

// 삽입 - 문단
var ID_RES_CONST_STRING_INSERT_PARAGRAPH = "문단";

// 서식 - 글자모양 - 보통모양 버튼 텍스트
var ID_RES_CONST_STRING_NORMAL = "보통모양";							//170

//표 - 표 텍스트로 변환
var ID_RES_CONST_STRING_TABLE_CONVERT_TEXT = "표 텍스트로 변환";

// 테이블생성 Layer(tablesize) 리소스 선언
var ID_RES_TABLE_SIZE_SELECT = "선 택";
var ID_RES_TABLE_SIZE_CANCEL = "취 소";

// 툴빌더(toolbuilder) 리소스 선언
var ID_RES_TOOL_STRING_MENU_FILE = "파일";
var ID_RES_TOOL_STRING_MENU_EDIT = "편집";							//175
var ID_RES_TOOL_STRING_MENU_VIEW = "보기";
var ID_RES_TOOL_STRING_MENU_INSERT = "삽입";
var ID_RES_TOOL_STRING_MENU_BASIC = "서식";
var ID_RES_TOOL_STRING_MENU_TABLE = "표";
var ID_RES_TOOL_STRING_MENU_HELP = "도움말";							//180
var ID_RES_TOOL_STRING_TAB_PREVIEW = "미리보기";
var ID_RES_TOOL_STRING_TAB_EDIT = "편집보기";
var ID_RES_TOOL_STRING_TAB_SOURCE = "HTML보기";

// 사용자메세지(usermsg) 리소스 선언
var ID_RES_USER_MSG_STRING_ALERT_CUT = "브라우저 보안 설정상 실행할 수 없습니다\nCtrl+X 키보드 명령어로는 실행하실 수는 있습니다";
var ID_RES_USER_MSG_STRING_ALERT_COPY = "브라우저 보안 설정상 실행할 수 없습니다\nCtrl+C 키보드 명령어로는 실행하실 수는 있습니다";	//185
var ID_RES_USER_MSG_STRING_ALERT_PASTE = "브라우저 보안 설정으로 인해 클립보드에 접근이 제한되어 있습니다.\n키보드(Ctrl+V)를 이용하여 주시기 바랍니다.";
var ID_RES_USER_MSG_STRING_WARNING_SCRIPT = "소스 코드상에 스크립트를 포함할 수 없습니다\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_MEDIA = "동영상 삽입은 IE 6,7,8 만 지원됩니다\n";
var ID_RES_USER_MSG_STRING_WARNING_NO_IFRAME = "소스 코드상에 iframe 태그를 포함할 수 없습니다\n";
var ID_RES_USER_MSG_STRING_WARNING_NO_SOURCE_EDIT = "양식폼 사용자 모드에서는 소스창을 사용할 수 없습니다\n";				//190
//var ID_RES_USER_MSG_STRING_WARNING_NO_FLASH_FF_2 = "파이어폭스에서는 3버전 이상부터 지원됩니다\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_FLASH_FF_EDIT = "파이어폭스 편집모드 설정상 지원되지 않습니다\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_SUPPORT_FORM_MODE = "코드검사는 양식관리자 또는 사용자모드에서는 지원되지 않습니다\n";
//var ID_RES_USER_MSG_STRING_WARNING_INVALID_ATTIRIBUTE_CHARACTER = "속성값으로 <,>,&,\',\" 등은 사용할 수 없습니다\n";
//var ID_RES_USER_MSG_STRING_WARNING_INVALID_COLOR_CODE = "유효한 색상코드를 입력하셔야 합니다.\n 예) #0099ff\n";		//195
//var ID_RES_USER_MSG_STRING_WARNING_IN_CONTROL_KEY_NO_SOURCE_EDIT = "키보드 제어용에서는 소스창을 사용할 수 없습니다";

// 문서보정(leftviewui) 리소스 선언
var ID_RES_ADJUST_VIEW_CLOSE = "닫기";

// 편집창 Title 리소스 선언
var ID_RES_EDIT_TITLE_STRING = "글입력부분";

var ID_RES_PROP_BUILDER_BLOCK_PROP_ITEM_APPLY = "적용";

var ID_RES_CONST_STRING_ALIGN = "정렬";								//200

// 양식 저작(Form Table) 리소스 선언
var ID_RES_PROP_FORM_WIN_TITLE = "양식 레이아웃";
var ID_RES_PROP_TAG_SELECT_WIN_TITLE = "목록 상자";
var ID_RES_PROP_MAPPING_CODE_WIN_TITLE = "양식 코드";
var ID_RES_PROP_MAPPING_CSS_WIN_TITLE = "양식 CSS 설정";
var ID_RES_PROP_TEMPLETE_FORM_WIN_TITLE = "양식 템플릿";					//205

// 컨텍스트 메뉴
var ID_RES_PROP_INSERT_IMAGE = "그림 속성";
var ID_RES_PROP_INSERT_FILE = "파일 속성";

var ID_RES_DIALOG_BTN_OK = "확인";
var ID_RES_DIALOG_BTN_CANCEL = "취소";
var ID_RES_DIALOG_BTN_NOCOLOR = "색 없음";								//210
var ID_RES_DIALOG_TAB_GENERAL = "일반";
var ID_RES_DIALOG_TAB_BORDER = "테두리";
var ID_RES_DIALOG_TAB_BACKGROUND = "배경";
var ID_RES_DIALOG_FORM_LIST1 = "샘플항목1";
var ID_RES_DIALOG_FORM_LIST2 = "샘플항목2";								//215
var ID_RES_DIALOG_FORM_LIST3 = "샘플항목3";
var ID_RES_DIALOG_MAPPINGCODE_TAB1 = "전자결재양식";
var ID_RES_DIALOG_MAPPINGCODE_TAB2 = "공문양식";
var ID_RES_DIALOG_CONFIRM_SAVE = "<p>작성중인 내용이 있습니다.</p><p>저장하시겠습니까?</p>";
var ID_RES_DIALOG_CONFIRM_YES = "예";								//220
var ID_RES_DIALOG_CONFIRM_NO = "아니오";
var ID_RES_DIALOG_CONFIRM_EMPTY_DOC = "문서가 비어있습니다. 확인해 주세요.";
var ID_RES_DIALOG_ALERT_SELECTFILE = "파일을 선택 해 주세요.";
var ID_RES_DIALOG_CONFIRM_FILE_DELETE_CONTENT = "파일을 불러오면 작성중인 내용이 삭제됩니다.\n파일을 불러 오시겠습니까?";
var ID_RES_DIALOG_ALERT_ALLOWFILES = "파일은 업로드 불가합니다.\n업로드 가능 파일";	//225
var ID_RES_DIALOG_ALERT_SELECTIMAGE = "이미지파일을 선택한 후 업로드 버튼을 클릭해 주세요.";
var ID_RES_DIALOG_ALERT_SELECT_VALID_IMAGE = "정상적인 이미지를 삽입해주세요.";
var ID_RES_DIALOG_ALERT_FIND_INPUT_TEXT = "찾을 내용을 입력 해 주세요.";
var ID_RES_DIALOG_ALERT_FIND_ERROR = "검색 중 에러가 발생했습니다.";
var ID_RES_DIALOG_ALERT_FIND_NOTHING = "해당 내용을 찾지 못했습니다.";			//230
var ID_RES_DIALOG_CONFIRM_FIND_END = "문서의 끝까지 찾았습니다.\n문서 처음부터 계속 찾으시겠습니까?";
var ID_RES_DIALOG_CONFIRM_FIND_FIRST = "문서의 처음까지 찾았습니다.\n문서 끝부터 계속 찾으시겠습니까?";
var ID_RES_DIALOG_ALERT_REPLACE_INPUT_TEXT = "바꿀 내용을 입력 해 주세요.";
var ID_RES_DIALOG_ALERT_REPLACE_ERROR = "바꾸기 진행 중 에러가 발생했습니다.";
var ID_RES_DIALOG_ALERT_REPLACEALL_COMPLETE = "모두 바꾸기가 완료되었습니다.";	//235
var ID_RES_DIALOG_ALERT_REPLACE_N = "개 항목이 바뀌었습니다.";
var ID_RES_DIALOG_TITLE_FIND_REPLACE = "찾기 및 바꾸기";
var ID_RES_DIALOG_BTN_REPLACEALL = "모두바꾸기";
var ID_RES_DIALOG_BTN_FIND_NEXT = "다음찾기";
var ID_RES_DIALOG_TITLE_EXT_MOVIE = "외부 동영상";						//240
var ID_RES_DIALOG_TITLE_FILE_INSERT = "파일 삽입";
var ID_RES_DIALOG_BTN_INSERT = "넣기";
var ID_RES_DIALOG_TITLE_WEBEDITOR_INFO = "Douzone Web Editor 정보";

var ID_RES_DIALOG_LIST_TITLE_FORM_AREA = "양식 영역";
var ID_RES_DIALOG_LIST_TITLE_FORM_SELECT = "양식 선택";					//245
var ID_RES_DIALOG_ALERT_SELECT_DOCFORM = "서식 양식을 선택 해 주세요.";
var ID_RES_DIALOG_CONFIRM_DOCFORM_DELETE_CONTENT = "서식 양식을 삽입하면 편집하던 문서 내용이 삭제됩니다.\n삽입 하시겠습니까?";
var ID_RES_DIALOG_ALERT_SELECT_LAYOUT_DESIGN = "레이아웃 디자인을 선택 해 주세요.";
var ID_RES_DIALOG_CONFIRM_LAYOUT_DELETE_CONTENT = "레아아웃을 삽입하면 편집하던 문서 내용이 삭제됩니다.\n삽입 하시겠습니까?";

var ID_RES_DIALOG_STRING_FILE_PATH = "파일 경로";						//250
var ID_RES_DIALOG_STRING_URL_INPUT = "URL 입력";
var ID_RES_DIALOG_STRING_UPLOAD = "업로드";
var ID_RES_DIALOG_STRING_SIZE = "크기";
var ID_RES_DIALOG_STRING_WIDTH = "너비";
var ID_RES_DIALOG_STRING_HEIGHT = "높이";								
var ID_RES_DIALOG_STRING_KEEP_RATIO = "비율 유지";
var ID_RES_DIALOG_STRING_SET_ORG = "원래대로";
var ID_RES_DIALOG_STRING_MARGIN = "여백";
var ID_RES_DIALOG_STRING_MARGIN_LEFT = "왼쪽여백";
var ID_RES_DIALOG_STRING_MARGIN_TOP = "위쪽여백";						//260
var ID_RES_DIALOG_STRING_MARGIN_RIGHT = "오른쪽여백";	
var ID_RES_DIALOG_STRING_MARGIN_BOTTOM = "아래쪽여백";
var ID_RES_DIALOG_STRING_ALIGN_BASIC = "기본";
var ID_RES_DIALOG_STRING_ALIGN_LEFT = "왼쪽";
var ID_RES_DIALOG_STRING_ALIGN_CENTER = "가운데";
var ID_RES_DIALOG_STRING_ALIGN_RIGHT = "오른쪽";
var ID_RES_DIALOG_ALERT_MAX_VALUE = "최대값을 벗어났습니다.\n최대값 : ";
var ID_RES_DIALOG_ALERT_MIN_VALUE = "최소값을 벗어났습니다.\n최소값 : ";
var ID_RES_DIALOG_ALERT_NUMBER_ONLY = "숫자만 입력 가능합니다.";
var ID_RES_DIALOG_ALERT_SELECT_VALID_URL = "이미지 URL을 다시 한번 확인 해 주세요!";	//270
var ID_RES_DIALOG_ALERT_UPLOAD_ERROR = "업로드시 오류가 발생했습니다. 다시 한번 시도해 주세요.";
var ID_RES_DIALOG_ALERT_INSERT_IMAGE = "이미지를 먼저 등록해주세요.";
var ID_RES_DIALOG_STRING_NO_STYLE_TEXT = "서식 없는 텍스트";
var ID_RES_DIALOG_STRING_HTML_STYLE_TEXT = "HTML 형식";
var ID_RES_DIALOG_STRING_FIND_TEXT = "찾을 내용";
var ID_RES_DIALOG_STRING_REPLACE_TEXT = "바꿀 내용";
var ID_RES_DIALOG_STRING_FIND_OPTION = "검색 옵션";
var ID_RES_DIALOG_STRING_CASESENSITIVE = "대소문자 구분";
var ID_RES_DIALOG_STRING_COMPLETEWORD = "온전한 낱말";
var ID_RES_DIALOG_STRING_IGNORESPACE = "띄어쓰기 무시";							//280
var ID_RES_DIALOG_STRING_FIND_DERECTION = "검색 방향";
var ID_RES_DIALOG_STRING_FIND_DOWN = "아래쪽";
var ID_RES_DIALOG_STRING_FIND_UP = "위쪽";
var ID_RES_DIALOG_STRING_INPUT_SOURCE = "소스 입력";
var ID_RES_DIALOG_STRING_MOVIE_INPUT_GUIDE = "object 또는 iframe 소스코드 입력해 주세요.";
var ID_RES_DIALOG_STRING_INPUT_MOVIE_SOURCE = "동영상 소스를 입력 해 주세요.";
var ID_RES_DIALOG_STRING_VIEW_TEXT = "표시할 텍스트";
var ID_RES_DIALOG_ALERT_ALLOW_FORMAT = "포멧만 지원합니다.";
var ID_RES_DIALOG_STRING_CHARACTER_AREA = "문자 영역";
var ID_RES_DIALOG_STRING_CHARACTER_SELECT = "문자 선택";					//290
var ID_RES_DIALOG_STRING_RECECT_USE_CHARACTER = "최근에 사용한 문자";

var ID_RES_DIALOG_ALERT_SELECT_CHARACTER = "문자를 선택해 주세요.";
var ID_RES_CONST_STRING_CHARACTER_GENERAL = "일반/기호";
var ID_RES_CONST_STRING_CHARACTER_ENG_NUMBER = "영어/숫자";
var ID_RES_CONST_STRING_CHARACTER_GREEK = "그리스어";
var ID_RES_CONST_STRING_CHARACTER_LINE = "선문자";
var ID_RES_CONST_STRING_CHARACTER_UNIT = "단위기호";
var ID_RES_CONST_STRING_CHARACTER_CIRCLE = "원문자";
var ID_RES_CONST_STRING_CHARACTER_BRAKETCHAR = "괄호문자";
var ID_RES_CONST_STRING_CHARACTER_FRACTION_SCRIPT = "분수/첨자";			//300
var ID_RES_CONST_STRING_CHARACTER_ARROW = "화살표";
var ID_RES_CONST_STRING_CHARACTER_BRAKET = "괄호";
var ID_RES_CONST_STRING_CHARACTER_MATH = "수학연산";
var ID_RES_CONST_STRING_CHARACTER_PUNCTUATION_MARKS = "문장부호";
var ID_RES_CONST_STRING_CHARACTER_CURRENCY = "화폐기호";

var ID_RES_DIALOG_STRING_BOOKMARK_NAME = "책갈피 이름";
var ID_RES_DIALOG_STRING_BOOKMARK_LIST = "책갈피 목록";
var ID_RES_DIALOG_STRING_MOVE = "이동";
var ID_RES_DIALOG_STRING_BOOKMARK_SORT_STANDARD = "책갈피 정렬 기준";
var ID_RES_DIALOG_STRING_NAME = "이름";									//310
var ID_RES_DIALOG_STRING_POSITION = "위치";
var ID_RES_DIALOG_ALERT_INPUT_BOOKMARK_NAME = "책갈피 이름을 입력해 주세요";
var ID_RES_DIALOG_ALERT_INPUT_SELECT_DELTE_BOOKMARK_ITEM = "북마크 목록에서 삭제할 항목을 선택해 주세요";
var ID_RES_DIALOG_ALERT_INPUT_SELECT_MOVE_BOOKMARK_ITEM = "북마크 목록에서 이동할 항목을 선택해 주세요";

var ID_RES_DIALOG_STRING_LINK_TYPE = "링크 종류";
var ID_RES_DIALOG_STRING_WEB_ADDR = "웹 주소";
var ID_RES_DIALOG_STRING_LINK_TARGET = "연결 문서 열기";
var ID_RES_DIALOG_STRING_LINK_CURRENT_WINDOW = "같은 창으로";
var ID_RES_DIALOG_STRING_LINK_NEW_WINDOW = "새 창으로";
var ID_RES_DIALOG_STRING_LINK_NO_CONNECT = "연결 안함";						//320
var ID_RES_DIALOG_STRING_LIST_SELECT = "선택";
var ID_RES_DIALOG_ALERT_SELECT_BOOKMARK = "책갈피를 선택해 주세요";
var ID_RES_DIALOG_ALERT_INPUT_WEB_ADDR = "웹주소를 입력해 주세요";

var ID_RES_DIALOG_STRING_LETTERSPACING = "자간";
var ID_RES_DIALOG_STRING_BASIC = "기본";
var ID_RES_DIALOG_STRING_PROPERTY = "속성";
var ID_RES_DIALOG_STRING_FONT_STYLE_PREVIEW = "가나다ABCabc123※○";

var ID_RES_DIALOG_STRING_ALIGN_TYPE = "정렬 방식";
var ID_RES_DIALOG_STRING_NORMAL = "보통";
var ID_RES_DIALOG_STRING_SPACING = "간격";								//330
var ID_RES_DIALOG_STRING_LINEHEIGHT = "줄간격";
var ID_RES_DIALOG_STRING_PARAGRAPH_TOP = "문단위";
var ID_RES_DIALOG_STRING_PARAGRAPH_BOTTOM = "문단아래";
var ID_RES_DIALOG_STRING_FIRST_PARAGRAPH = "첫줄";

var ID_RES_DIALOG_STRING_NONE = "없음";
var ID_RES_DIALOG_STRING_VERSION = "버전";


var ID_RES_DIALOG_STRING_FORM_BASE_SIZE = "기준 크기 / 높이";
var ID_RES_DIALOG_STRING_FORM_HEIGHT_MSG = "높이 설정은<br />양식 생성시 반영됨";
var ID_RES_DIALOG_STRING_FORM_OUTLINE = "외곽선";
var ID_RES_DIALOG_STRING_FORM_TYPE = "유형";								//340
var ID_RES_DIALOG_STRING_FORM_COLOR = "색상";
var ID_RES_DIALOG_STRING_FORM_MULTI_SELECT = "다중선택 :<br />&nbsp;&nbsp;Ctrl키 + 객체 선택";
var ID_RES_DIALOG_STRING_FORM_MULTI_OTHER_SELECT = "다중선택 :<br />&nbsp;&nbsp;객체 선택->shift 키-><br />&nbsp;&nbsp;다른 객체 선택";
var ID_RES_DIALOG_STRING_FORM_COPY_PASTE = "복사/붙여넣기 :<br />&nbsp;&nbsp;객체 선택 후 Ctrl키 + V";
var ID_RES_DIALOG_STRING_FORM_COPY_MOVE = "이동 :<br />&nbsp;&nbsp;상하좌우 화살표 키";
var ID_RES_DIALOG_STRING_FORM_RESIZE = "크기조정 :<br />&nbsp;&nbsp;Ctrl 키 + 화살표 키";
var ID_RES_DIALOG_STRING_FORM_PRE_APPLY = "미리적용";
var ID_RES_DIALOG_ALERT_FORM_SIZE = "크기(width) 단위가 % 인 경우만 지원하고 있습니다.";

var ID_RES_PROP_TAG_STRING_ROW_NUM = "줄 수";
var ID_RES_PROP_TAG_STRING_COL_NUM = "칸 수";								//350
var ID_RES_PROP_TAG_STRING_ROW_COL = "줄 / 칸";
var ID_RES_PROP_TAG_STRING_SIZE_DEFINE = "크기 지정";
var ID_RES_PROP_TAG_STRING_WIDTH_UNIT = "너비 단위";
var ID_RES_PROP_TAG_STRING_ALL_CELL_INNER_MARGIN = "모든 셀의 안 여백";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN = "정렬";

var ID_RES_PROP_TAG_STRING_TABLE_ALIGN_NONE = "없음";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN_LEFT = "왼쪽";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN_CENTER = "가운데";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN_RIGHT = "오른쪽";

var ID_RES_PROP_TAG_STRING_FILL = "채우기";								//360
var ID_RES_PROP_TAG_STRING_NO_COLOR_FILL = "색 채우기 없음";
var ID_RES_PROP_TAG_STRING_COLOR = "색";
var ID_RES_PROP_TAG_STRING_FACE_COLOR = "면 색";

var ID_RES_PROP_TAG_STRING_IMAGE = "그림";
var ID_RES_PROP_TAG_STRING_USER_IMAGE = "그림 사용";
var ID_RES_PROP_TAG_STRING_IMAGE_FILE = "그림 파일";
var ID_RES_PROP_TAG_STRING_FILL_TYPE = "채우기 유형";
var ID_RES_PROP_TAG_STRING_REPEAT = "반복";
var ID_RES_PROP_TAG_STRING_REPEAT_HOR = "가로 반복";
var ID_RES_PROP_TAG_STRING_REPEAT_VER = "세로 반복";						//370
var ID_RES_PROP_TAG_STRING_REPEAT_NO = "반복 안함";

var ID_RES_PROP_TAG_LIST_NUM = "목록 개수";
var ID_RES_PROP_TAG_LIST_CONTENT = "목록 내용";

var ID_RES_PROP_TAG_ADD_ROW = "줄 추가하기";
var ID_RES_PROP_TAG_UP = "위쪽";
var ID_RES_PROP_TAG_DOWN = "아래쪽";
var ID_RES_PROP_TAG_ADD_COL = "칸 추가하기";

var ID_RES_PROP_TAG_SET_INNER_MARGIN = "안 여백 지정";

var ID_RES_PROP_TAG_STRING_LEFT = "왼쪽";
var ID_RES_PROP_TAG_STRING_TOP = "위쪽";									//380
var ID_RES_PROP_TAG_STRING_RIGHT = "오른쪽";								
var ID_RES_PROP_TAG_STRING_BOTTOM = "아래쪽";

var ID_RES_PROP_TAG_STRING_ALIGN_HOR = "가로정렬";
var ID_RES_PROP_TAG_STRING_ALIGN_VER = "세로정렬";
var ID_RES_PROP_TAG_STRING_ALIGN_TOP = "위쪽 맞춤";
var ID_RES_PROP_TAG_STRING_ALIGN_MIDDLE = "가운데 맞춤";
var ID_RES_PROP_TAG_STRING_ALIGN_BOTTOM = "아래쪽 맞춤";

var ID_RES_PROP_TAG_STRING_APPLY_RANGE= "적용 범위";
var ID_RES_PROP_TAG_STRING_SELECTED_CELL = "선택된 셀";
var ID_RES_PROP_TAG_STRING_ALL_CELL = "모든 셀";							//390

var ID_RES_PROP_TAG_ALERT_UNDER_100PER = "100% 이하로 설정하세요.";

var ID_RES_PROP_TAG_STRING_SELECT_CELL_EDITOR = "적용할 셀을 편집창에서 선택하세요.";
var ID_RES_PROP_TAG_STRING_NO_CALC_SELECTED_CELL = "계산 불가한 항목이 선택되었습니다.";
var ID_RES_PROP_TAG_STRING_SELECT_CELL = "셀 선택";
var ID_RES_PROP_TAG_STRING_CALC_TYPE = "계산 방법";
var ID_RES_PROP_TAG_STRING_CALC_SUM = "합계";
var ID_RES_PROP_TAG_STRING_CALC_AVG = "평균";
var ID_RES_PROP_TAG_STRING_CALC_MUL = "곱";
var ID_RES_PROP_TAG_STRING_CALC_RESULT = "계산 결과";
var ID_RES_PROP_TAG_STRING_SPLIT_ROW_COL = "줄/칸 나누기";					//400

var ID_RES_PROP_TEMPLETE_STRING_FORM_SUBJECT = "양식 제목";
var ID_RES_PROP_TEMPLETE_STRING_SUBJECT = "제목";
var ID_RES_PROP_TEMPLETE_STRING_SIZE_ITEM_SET = "크기 / 항목 설정";
var ID_RES_PROP_TEMPLETE_STRING_AUTO = "자동";
var ID_RES_PROP_ALERT_ONLY_NUMBER_CALC = "숫자만 계산이 가능합니다.";

var ID_RES_DIALOG_SHORTCUTS_TITLE = "단축키";
var ID_RES_DIALOG_SHORTCUTS_MENU_PATH = "메뉴경로";
var ID_RES_DIALOG_SHORTCUTS_FUNCTION = "기능";
var ID_RES_DIALOG_SHORTCUTS_BASIC = "기본 단축키";
var ID_RES_DIALOG_SHORTCUTS_SPACE = "빈칸 삽입";							//410
var ID_RES_DIALOG_SHORTCUTS_ENTER = "문단 나누기";
var ID_RES_DIALOG_SHORTCUTS_LEFT = "한 글자 왼쪽으로";
var ID_RES_DIALOG_SHORTCUTS_RIGHT = "한 글자 오른쪽으로";
var ID_RES_DIALOG_SHORTCUTS_DOWN = "한 줄 아래로";
var ID_RES_DIALOG_SHORTCUTS_UP = "한 줄 위로";
var ID_RES_DIALOG_SHORTCUTS_RIGHT_WORD = "한 단어 오른쪽으로";
var ID_RES_DIALOG_SHORTCUTS_LEFT_WORD = "한 단어 왼쪽으로";
var ID_RES_DIALOG_SHORTCUTS_DOWN_PARAGRAPH = "한 문단 아래로";
var ID_RES_DIALOG_SHORTCUTS_UP_PARAGRAPH = "한 문단 위로";
var ID_RES_DIALOG_SHORTCUTS_HOME = "줄 처음으로";							//420
var ID_RES_DIALOG_SHORTCUTS_END = "줄 끝으로";
var ID_RES_DIALOG_SHORTCUTS_HOME_PAGE = "화면 처음으로";
var ID_RES_DIALOG_SHORTCUTS_END_PAGE = "화면 끝으로";
var ID_RES_DIALOG_SHORTCUTS_DELETE = "뒷글자 지우기";
var ID_RES_DIALOG_SHORTCUTS_BACKSPACE = "앞글자 지우기";
var ID_RES_DIALOG_SHORTCUTS_DELETE_WORD = "한 단어 지우기";
var ID_RES_DIALOG_SHORTCUTS_DELETE_PREV_WORD = "앞 단어 지우기";

var ID_RES_DIALOG_SHORTCUTS_FILE = "파일 메뉴";
var ID_RES_DIALOG_SHORTCUTS_EDIT = "편집 메뉴";
var ID_RES_DIALOG_SHORTCUTS_INSERT = "삽입 메뉴";							//430
var ID_RES_DIALOG_SHORTCUTS_STYLE = "서식 메뉴";	
var ID_RES_DIALOG_SHORTCUTS_TABLE = "표 메뉴";

var ID_RES_CONST_STRING_CLEAR = "해제";

var ID_RES_CONST_STRING_INCREASE_LETTERSPACING = "자간 넓게";
var ID_RES_CONST_STRING_DECREASE_LETTERSPACING = "자간 좁게";

var ID_RES_CONST_STRING_INCREASE_MARGIN_LEFT = "왼쪽 여백 늘리기";
var ID_RES_CONST_STRING_DECREASE_MARGIN_LEFT = "왼쪽 여백 줄이기";
var ID_RES_CONST_STRING_INCREASE_MARGIN_RIGHT = "오른쪽 여백 늘리기";
var ID_RES_CONST_STRING_DECREASE_MARGIN_RIGHT = "오른쪽 여백 줄이기";

var ID_RES_CONST_STRING_FIRST_PARAGRAPH_OUTDENT = "첫 줄 내어 쓰기";			//440
var ID_RES_CONST_STRING_FIRST_PARAGRAPH_INDENT = "첫 줄 들여 쓰기";

var ID_RES_CONST_STRING_INCREASE_LINEHEIGHT = "줄 간격 넓게";
var ID_RES_CONST_STRING_DECREASE_LINEHEIGHT = "줄 간격 좁게";

var ID_RES_CONST_STRING_SELECT_CURRENT_CELL = "현재 셀 선택";
var ID_RES_CONST_STRING_MOVE_CELL_UNIT = "셀 단위로 커서 이동";
var ID_RES_CONST_STRING_MOVE_NEXT_CELL = "표 안에서 다른 셀로 이동(정방향)";
var ID_RES_CONST_STRING_MOVE_PREV_CELL = "표 안에서 다른 셀로 이동(역방향)";

var ID_RES_CONST_STRING_BLOCK_ALL_COL = "칸 전체 블록";
var ID_RES_CONST_STRING_BLOCK_ALL_ROW = "줄 전체 블록";
var ID_RES_CONST_STRING_MULTI_CELL_SELECT = "다중 셀 선택 시";				//450
var ID_RES_CONST_STRING_ARROW_KEY = "방향키";

var ID_RES_CONST_STRING_STANDARD = "표준";
var ID_RES_CONST_STRING_USER_DEFINE = "사용자 정의";
var ID_RES_CONST_STRING_USER_SET = "사용자 지정";
var ID_RES_CONST_STRING_REPLACE_CASE_CAPITAL = "모두 대문자로";
var ID_RES_CONST_STRING_REPLACE_CASE_SMALL = "모두 소문자로";
var ID_RES_CONST_STRING_REPLACE_CASE_REVERSE = "대소문자 바꿈";
var ID_RES_CONST_STRING_REPLACE_CASE_LETTER = "단어 첫 글자 대문자로";
var ID_RES_CONST_STRING_REPLACE_CASE_SENTENCE = "문장 첫 글자 대문자로";
var ID_RES_CONST_STRING_REPLACE_CASE_PARAGRAPH = " 문단 첫 글자 대문자로";		//460
var ID_RES_CONST_BTN_DELETE = "삭제";
var ID_RES_CONST_INSERT_IMAGE_PARAGRAPH_ALIGN = "본문 정렬";

var ID_RES_CONST_STRING_NEW_COLOR = "새 색";
var ID_RES_CONST_STRING_CURRENT_COLOR = "현재 색";
var ID_RES_CONST_STRING_OTHER_COLOR = "다른 색";
var ID_RES_CONST_STRING_RECENT_COLOR = "최근 사용한 색";
var ID_RES_CONST_STRING_ADD_USER_COLOR = "사용자 지정 색에 추가";
var ID_RES_CONST_STRING_RED = "빨강";
var ID_RES_CONST_STRING_GREEN = "녹색";
var ID_RES_CONST_STRING_BLUE = "파랑";									//470
var ID_RES_CONST_STRING_HUE = "색상";
var ID_RES_CONST_STRING_SATURATION = "채도";
var ID_RES_CONST_STRING_LIGHTNESS = "명도";

var ID_RES_CONST_MSG_ALERT_NO_RECENT_COLOR = "최근 사용한 색이 없습니다.";
var ID_RES_CONST_MSG_ALERT_DELETE_RECENT_COLOR = "최근 사용한 색을 모두 삭제하시겠습니까?";

var ID_RED_CONST_STRING_ALIGN_LEFT_TOP		= "왼쪽 위";
var ID_RED_CONST_STRING_ALIGN_LEFT_MIDDLE	= "왼쪽 가운데";
var ID_RED_CONST_STRING_ALIGN_LEFT_BOTTOM	= "왼쪽 아래";
var ID_RED_CONST_STRING_ALIGN_CENTER_TOP	= "위쪽 가운데";
var ID_RED_CONST_STRING_ALIGN_CENTER_MIDDLE = "정가운데";					//480
var ID_RED_CONST_STRING_ALIGN_CENTER_BOTTOM = "아래쪽 가운데";
var ID_RED_CONST_STRING_ALIGN_RIGHT_TOP		= "오른쪽 위";
var ID_RED_CONST_STRING_ALIGN_RIGHT_MIDDLE	= "오른쪽 가운데";
var ID_RED_CONST_STRING_ALIGN_RIGHT_BOTTOM	= "오른쪽 아래";
var ID_RED_CONST_STRING_TABLE_CELL_BACKCOLOR	= "셀 배경 색";

var ID_RES_CONST_STRING_COLOR_STANDARD = "표준 색";
var ID_RES_CONST_STRING_COLOR_THEME = "테마 색";

var ID_RES_CONST_STRING_EMOTICONS_FEEL = "감정";
var ID_RES_CONST_STRING_EMOTICONS_ACTION = "행동";
var ID_RES_CONST_STRING_EMOTICONS_ETC = "기타";							//490
var ID_RES_DIALOG_STRING_CATEGORY_AREA = "분류";
var ID_RES_DIALOG_STRING_EMOTICON_SELECT = "이모티콘 선택";
var ID_RES_DIALOG_STRING_RECECT_USE_EMOTICONS = "최근에 사용한 이모티콘";

var ID_RES_UI_TOGGLE_STRING_RIBBON = "리본 메뉴 스타일";
var ID_RES_UI_TOGGLE_STRING_TOOLBAR = "툴바 메뉴 스타일";
var ID_RES_CONST_STRING_PRINT_PAGE_BREAK = "인쇄 페이지 나누기";
var ID_RES_CONST_STRING_VIEW_RULERBAR = "눈금자 보기";
var ID_RES_DIALOG_STRING_CASCADE_ORDERLIST = "다단계 목록";
var ID_RES_CONST_STRING_COPY_EXT_STYLE = "서식 복사";

var ID_RES_CONST_STRING_BORDER_TYPE = "테두리 종류";					//500
var ID_RES_CONST_STRING_BORDER_THICKNESS = "테두리 두께";
var ID_RES_CONST_STRING_BORDER_COLOR = "테두리 색";
var ID_RES_CONST_STRING_RESET_PICTURE = "그림 원래대로";

var ID_RES_CONST_STRING_NO_LINE = "선 없음";
var ID_RES_CONST_STRING_SOLID_LINE = "실선";
var ID_RES_CONST_STRING_DASHED_LINE = "파선";
var ID_RES_CONST_STRING_DOTTED_LINE = "점선";
var ID_RES_CONST_STRING_DOUBLE_LINE = "이중선";

var ID_RES_CONST_STRING_TABLE_SELECT_CELL = "셀 선택";
var ID_RES_CONST_STRING_TABLE_SELECT_COL = "열 선택";					//510
var ID_RES_CONST_STRING_TABLE_SELECT_ROW = "행 선택";
var ID_RES_CONST_STRING_TABLE_SELECT_TABLE = "표 선택";

var ID_RES_CONST_STRING_IMAGE_TO_TABLE = "폼봇";
var ID_RES_CONST_STRING_HELP_IMAGE_TO_TABLE = "양식추출 도움말";

var ID_RES_CONST_MSG_ALERT_NO_SUPPORT_IN_LIST = "글머리표나 문단번호모양이 지정된 문단에는 해당기능을 지원하지 않습니다.";

var ID_RES_CONST_STRING_CANNOT_UPLOAD_FILE_TYPE = "파일은 업로드 할수 없는 파일입니다.\n * 사용가능파일:";
var ID_RES_CONST_STRING_CANNOT_READ_DOCUMENT_FORMAT = "양식 문서 포맷을 표현할 수 없습니다";
var ID_RES_CONST_STRING_NO_FILES_UPLOADED = "업로드된 파일이 없습니다.";
var ID_RES_CONST_STRING_KEEP_ORG_HEIGHT = "원본 높이 유지";
var ID_RES_CONST_STRING_NEW_BLOCK_REFERENCE_HEIGHT = "신규 블럭은<br />기준 높이로 설정";           //520
var ID_RES_CONST_STRING_BACKGROUND_COLOR = "배경색";
var ID_RES_CONST_STRING_LOSE_ALL_CONTINUE = "기존 작성한 내용은 초기화됩니다.\n계속 진행하시겠습니까?";

var ID_RES_CONST_STRING_ENTER_SUBJECT = "제목을 입력해 주세요";
var ID_RES_CONST_STRING_ENTER_DETAIL = "내용을 입력해 주세요."

var ID_RES_CONST_STRING_TABLE_LOCK_EDIT_CELL = "셀 편집제한";
var ID_RES_CONST_STRING_NOT_EDITABLE_AREA = "편집이 제한된 영역입니다.";

var ID_RES_PROP_TAG_STRING_TABLE_ID_CLASS_DEFINE = "ID / Class 설정";
var ID_RES_PROP_TAG_STRING_TABLE_ID = "ID";
var ID_RES_PROP_TAG_STRING_TABLE_CLASS = "Class";
var ID_RES_DIALOG_ALERT_DUPLICATED_ID = "사용중인 ID 입니다.";

var ID_RES_DIALOG_CONFIRM_KEEP_PASTED_CONTENTS = "에디터 기본 사이즈를 초과하였습니다.\n붙여넣은 파일을 사용하시겠습니까?";

var ID_RES_DIALOG_STRING_CUSTOM_INPUT_BOX = "양식코드 편집";
var ID_RES_DIALOG_STRING_TAG_NAME = "태그 이름";
var ID_RES_DIALOG_STRING_TAG_FORMAT = "태그 형식";
var ID_RES_DIALOG_STRING_CONTRACTOR_TYPE = "계약자 구분 선택";
var ID_RES_DIALOG_STRING_TEXT_LENGTH = "글자 길이";
var ID_RES_DIALOG_STRING_FONT_FAMILY = "폰트";
var ID_RES_DIALOG_STRING_FONT_SIZE = "폰트 크기";
var ID_RES_DIALOG_STRING_FONT_WEIGHT = "폰트 굵기";
var ID_RES_DIALOG_STRING_READONLY = "읽기전용 여부";

var ID_RES_CONST_EXTERNAL_DATA_AREA = "외부 데이터 영역";